// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class ClientGroupInfo;
@class ClientGroupInfoBuilder;
@class ClientGroupMsg;
@class ClientGroupMsgBuilder;
@class ClientGroupUnReadCnt;
@class ClientGroupUnReadCntBuilder;
@class ClientMsgInfo;
@class ClientMsgInfoBuilder;
@class ClientOfflineFileInfo;
@class ClientOfflineFileInfoBuilder;
@class ClientUnReadInfo;
@class ClientUnReadInfoBuilder;
@class ClientUserInfo;
@class ClientUserInfoBuilder;
@class ClientUserStat;
@class ClientUserStatBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class ServerGroupInfo;
@class ServerGroupInfoBuilder;
@class ServerGroupMsg;
@class ServerGroupMsgBuilder;
@class ServerGroupUnReadCnt;
@class ServerGroupUnReadCntBuilder;
@class ServerMsgInfo;
@class ServerMsgInfoBuilder;
@class ServerOfflineFileInfo;
@class ServerOfflineFileInfoBuilder;
@class ServerUnReadInfo;
@class ServerUnReadInfoBuilder;
@class ServerUserInfo;
@class ServerUserInfoBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  ResultTypeRefuseReasonNone = 0,
  ResultTypeRefuseReasonNoMsgServer = 1,
  ResultTypeRefuseReasonMsgServerFull = 2,
  ResultTypeRefuseReasonNoDbServer = 3,
  ResultTypeRefuseReasonNoLoginServer = 4,
  ResultTypeRefuseReasonNoRouteServer = 5,
  ResultTypeRefuseReasonDbValidateFailed = 6,
  ResultTypeResuseReasonVersionTooOld = 7,
} ResultType;

BOOL ResultTypeIsValidValue(ResultType value);

typedef enum {
  UserTypeUserTypeNormal = 0,
} UserType;

BOOL UserTypeIsValidValue(UserType value);

typedef enum {
  KickReasonTypeKickReasonDuplicateUser = 1,
} KickReasonType;

BOOL KickReasonTypeIsValidValue(KickReasonType value);

typedef enum {
  OnlineListTypeOnlineListTypeFriendList = 1,
} OnlineListType;

BOOL OnlineListTypeIsValidValue(OnlineListType value);

typedef enum {
  UserStatTypeUserStatusOnline = 1,
  UserStatTypeUserStatusOffline = 2,
  UserStatTypeUserStatusLeave = 3,
} UserStatType;

BOOL UserStatTypeIsValidValue(UserStatType value);

typedef enum {
  SessionTypeSessionTypeSingle = 1,
  SessionTypeSessionTypeGroup = 2,
  SessionTypeSessionTypeTempGroup = 3,
} SessionType;

BOOL SessionTypeIsValidValue(SessionType value);

typedef enum {
  GroupTypeNormalGroup = 0,
  GroupTypeTemporaryGroup = 1,
} GroupType;

BOOL GroupTypeIsValidValue(GroupType value);


@interface ImbaseDefineRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IpAddr : PBGeneratedMessage {
@private
  BOOL hasIp_:1;
  BOOL hasPort_:1;
  NSString* ip;
  UInt32 port;
}
- (BOOL) hasIp;
- (BOOL) hasPort;
@property (readonly, strong) NSString* ip;
@property (readonly) UInt32 port;

+ (IpAddr*) defaultInstance;
- (IpAddr*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IpAddrBuilder*) builder;
+ (IpAddrBuilder*) builder;
+ (IpAddrBuilder*) builderWithPrototype:(IpAddr*) prototype;
- (IpAddrBuilder*) toBuilder;

+ (IpAddr*) parseFromData:(NSData*) data;
+ (IpAddr*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IpAddrBuilder : PBGeneratedMessageBuilder {
@private
  IpAddr* result;
}

- (IpAddr*) defaultInstance;

- (IpAddrBuilder*) clear;
- (IpAddrBuilder*) clone;

- (IpAddr*) build;
- (IpAddr*) buildPartial;

- (IpAddrBuilder*) mergeFrom:(IpAddr*) other;
- (IpAddrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IpAddrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp;
- (NSString*) ip;
- (IpAddrBuilder*) setIp:(NSString*) value;
- (IpAddrBuilder*) clearIp;

- (BOOL) hasPort;
- (UInt32) port;
- (IpAddrBuilder*) setPort:(UInt32) value;
- (IpAddrBuilder*) clearPort;
@end

@interface ClientUserInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasName_:1;
  BOOL hasNickName_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasDepartment_:1;
  BOOL hasUserUpdated_:1;
  BOOL hasUserType_:1;
  NSString* userId;
  NSString* name;
  NSString* nickName;
  NSString* avatarUrl;
  NSString* department;
  UInt32 userUpdated;
  UserType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasNickName;
- (BOOL) hasAvatarUrl;
- (BOOL) hasDepartment;
- (BOOL) hasUserType;
- (BOOL) hasUserUpdated;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* avatarUrl;
@property (readonly, strong) NSString* department;
@property (readonly) UserType userType;
@property (readonly) UInt32 userUpdated;

+ (ClientUserInfo*) defaultInstance;
- (ClientUserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientUserInfoBuilder*) builder;
+ (ClientUserInfoBuilder*) builder;
+ (ClientUserInfoBuilder*) builderWithPrototype:(ClientUserInfo*) prototype;
- (ClientUserInfoBuilder*) toBuilder;

+ (ClientUserInfo*) parseFromData:(NSData*) data;
+ (ClientUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientUserInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClientUserInfo* result;
}

- (ClientUserInfo*) defaultInstance;

- (ClientUserInfoBuilder*) clear;
- (ClientUserInfoBuilder*) clone;

- (ClientUserInfo*) build;
- (ClientUserInfo*) buildPartial;

- (ClientUserInfoBuilder*) mergeFrom:(ClientUserInfo*) other;
- (ClientUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ClientUserInfoBuilder*) setUserId:(NSString*) value;
- (ClientUserInfoBuilder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (ClientUserInfoBuilder*) setName:(NSString*) value;
- (ClientUserInfoBuilder*) clearName;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (ClientUserInfoBuilder*) setNickName:(NSString*) value;
- (ClientUserInfoBuilder*) clearNickName;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (ClientUserInfoBuilder*) setAvatarUrl:(NSString*) value;
- (ClientUserInfoBuilder*) clearAvatarUrl;

- (BOOL) hasDepartment;
- (NSString*) department;
- (ClientUserInfoBuilder*) setDepartment:(NSString*) value;
- (ClientUserInfoBuilder*) clearDepartment;

- (BOOL) hasUserType;
- (UserType) userType;
- (ClientUserInfoBuilder*) setUserType:(UserType) value;
- (ClientUserInfoBuilder*) clearUserType;

- (BOOL) hasUserUpdated;
- (UInt32) userUpdated;
- (ClientUserInfoBuilder*) setUserUpdated:(UInt32) value;
- (ClientUserInfoBuilder*) clearUserUpdated;
@end

@interface ServerUserInfo : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasNickName_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasDepartment_:1;
  BOOL hasUserId_:1;
  BOOL hasUserType_:1;
  BOOL hasUserUpdate_:1;
  NSString* name;
  NSString* nickName;
  NSString* avatarUrl;
  NSString* department;
  UInt32 userId;
  UInt32 userType;
  UInt32 userUpdate;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasNickName;
- (BOOL) hasAvatarUrl;
- (BOOL) hasDepartment;
- (BOOL) hasUserType;
- (BOOL) hasUserUpdate;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* avatarUrl;
@property (readonly, strong) NSString* department;
@property (readonly) UInt32 userType;
@property (readonly) UInt32 userUpdate;

+ (ServerUserInfo*) defaultInstance;
- (ServerUserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerUserInfoBuilder*) builder;
+ (ServerUserInfoBuilder*) builder;
+ (ServerUserInfoBuilder*) builderWithPrototype:(ServerUserInfo*) prototype;
- (ServerUserInfoBuilder*) toBuilder;

+ (ServerUserInfo*) parseFromData:(NSData*) data;
+ (ServerUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ServerUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerUserInfoBuilder : PBGeneratedMessageBuilder {
@private
  ServerUserInfo* result;
}

- (ServerUserInfo*) defaultInstance;

- (ServerUserInfoBuilder*) clear;
- (ServerUserInfoBuilder*) clone;

- (ServerUserInfo*) build;
- (ServerUserInfo*) buildPartial;

- (ServerUserInfoBuilder*) mergeFrom:(ServerUserInfo*) other;
- (ServerUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (ServerUserInfoBuilder*) setUserId:(UInt32) value;
- (ServerUserInfoBuilder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (ServerUserInfoBuilder*) setName:(NSString*) value;
- (ServerUserInfoBuilder*) clearName;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (ServerUserInfoBuilder*) setNickName:(NSString*) value;
- (ServerUserInfoBuilder*) clearNickName;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (ServerUserInfoBuilder*) setAvatarUrl:(NSString*) value;
- (ServerUserInfoBuilder*) clearAvatarUrl;

- (BOOL) hasDepartment;
- (NSString*) department;
- (ServerUserInfoBuilder*) setDepartment:(NSString*) value;
- (ServerUserInfoBuilder*) clearDepartment;

- (BOOL) hasUserType;
- (UInt32) userType;
- (ServerUserInfoBuilder*) setUserType:(UInt32) value;
- (ServerUserInfoBuilder*) clearUserType;

- (BOOL) hasUserUpdate;
- (UInt32) userUpdate;
- (ServerUserInfoBuilder*) setUserUpdate:(UInt32) value;
- (ServerUserInfoBuilder*) clearUserUpdate;
@end

@interface ClientUserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserStat_:1;
  NSString* userId;
  UserStatType userStat;
}
- (BOOL) hasUserId;
- (BOOL) hasUserStat;
@property (readonly, strong) NSString* userId;
@property (readonly) UserStatType userStat;

+ (ClientUserStat*) defaultInstance;
- (ClientUserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientUserStatBuilder*) builder;
+ (ClientUserStatBuilder*) builder;
+ (ClientUserStatBuilder*) builderWithPrototype:(ClientUserStat*) prototype;
- (ClientUserStatBuilder*) toBuilder;

+ (ClientUserStat*) parseFromData:(NSData*) data;
+ (ClientUserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUserStat*) parseFromInputStream:(NSInputStream*) input;
+ (ClientUserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientUserStatBuilder : PBGeneratedMessageBuilder {
@private
  ClientUserStat* result;
}

- (ClientUserStat*) defaultInstance;

- (ClientUserStatBuilder*) clear;
- (ClientUserStatBuilder*) clone;

- (ClientUserStat*) build;
- (ClientUserStat*) buildPartial;

- (ClientUserStatBuilder*) mergeFrom:(ClientUserStat*) other;
- (ClientUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ClientUserStatBuilder*) setUserId:(NSString*) value;
- (ClientUserStatBuilder*) clearUserId;

- (BOOL) hasUserStat;
- (UserStatType) userStat;
- (ClientUserStatBuilder*) setUserStat:(UserStatType) value;
- (ClientUserStatBuilder*) clearUserStat;
@end

@interface ServerUserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserStat_:1;
  UInt32 userId;
  UserStatType userStat;
}
- (BOOL) hasUserId;
- (BOOL) hasUserStat;
@property (readonly) UInt32 userId;
@property (readonly) UserStatType userStat;

+ (ServerUserStat*) defaultInstance;
- (ServerUserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerUserStatBuilder*) builder;
+ (ServerUserStatBuilder*) builder;
+ (ServerUserStatBuilder*) builderWithPrototype:(ServerUserStat*) prototype;
- (ServerUserStatBuilder*) toBuilder;

+ (ServerUserStat*) parseFromData:(NSData*) data;
+ (ServerUserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerUserStatBuilder : PBGeneratedMessageBuilder {
@private
  ServerUserStat* result;
}

- (ServerUserStat*) defaultInstance;

- (ServerUserStatBuilder*) clear;
- (ServerUserStatBuilder*) clone;

- (ServerUserStat*) build;
- (ServerUserStat*) buildPartial;

- (ServerUserStatBuilder*) mergeFrom:(ServerUserStat*) other;
- (ServerUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (ServerUserStatBuilder*) setUserId:(UInt32) value;
- (ServerUserStatBuilder*) clearUserId;

- (BOOL) hasUserStat;
- (UserStatType) userStat;
- (ServerUserStatBuilder*) setUserStat:(UserStatType) value;
- (ServerUserStatBuilder*) clearUserStat;
@end

@interface ClientUnReadInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUnreadCount_:1;
  NSString* userId;
  UInt32 unreadCount;
}
- (BOOL) hasUserId;
- (BOOL) hasUnreadCount;
@property (readonly, strong) NSString* userId;
@property (readonly) UInt32 unreadCount;

+ (ClientUnReadInfo*) defaultInstance;
- (ClientUnReadInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientUnReadInfoBuilder*) builder;
+ (ClientUnReadInfoBuilder*) builder;
+ (ClientUnReadInfoBuilder*) builderWithPrototype:(ClientUnReadInfo*) prototype;
- (ClientUnReadInfoBuilder*) toBuilder;

+ (ClientUnReadInfo*) parseFromData:(NSData*) data;
+ (ClientUnReadInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUnReadInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientUnReadInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientUnReadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientUnReadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientUnReadInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClientUnReadInfo* result;
}

- (ClientUnReadInfo*) defaultInstance;

- (ClientUnReadInfoBuilder*) clear;
- (ClientUnReadInfoBuilder*) clone;

- (ClientUnReadInfo*) build;
- (ClientUnReadInfo*) buildPartial;

- (ClientUnReadInfoBuilder*) mergeFrom:(ClientUnReadInfo*) other;
- (ClientUnReadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientUnReadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ClientUnReadInfoBuilder*) setUserId:(NSString*) value;
- (ClientUnReadInfoBuilder*) clearUserId;

- (BOOL) hasUnreadCount;
- (UInt32) unreadCount;
- (ClientUnReadInfoBuilder*) setUnreadCount:(UInt32) value;
- (ClientUnReadInfoBuilder*) clearUnreadCount;
@end

@interface ServerUnReadInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUnreadCount_:1;
  UInt32 userId;
  UInt32 unreadCount;
}
- (BOOL) hasUserId;
- (BOOL) hasUnreadCount;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 unreadCount;

+ (ServerUnReadInfo*) defaultInstance;
- (ServerUnReadInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerUnReadInfoBuilder*) builder;
+ (ServerUnReadInfoBuilder*) builder;
+ (ServerUnReadInfoBuilder*) builderWithPrototype:(ServerUnReadInfo*) prototype;
- (ServerUnReadInfoBuilder*) toBuilder;

+ (ServerUnReadInfo*) parseFromData:(NSData*) data;
+ (ServerUnReadInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUnReadInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ServerUnReadInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUnReadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerUnReadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerUnReadInfoBuilder : PBGeneratedMessageBuilder {
@private
  ServerUnReadInfo* result;
}

- (ServerUnReadInfo*) defaultInstance;

- (ServerUnReadInfoBuilder*) clear;
- (ServerUnReadInfoBuilder*) clone;

- (ServerUnReadInfo*) build;
- (ServerUnReadInfo*) buildPartial;

- (ServerUnReadInfoBuilder*) mergeFrom:(ServerUnReadInfo*) other;
- (ServerUnReadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerUnReadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (ServerUnReadInfoBuilder*) setUserId:(UInt32) value;
- (ServerUnReadInfoBuilder*) clearUserId;

- (BOOL) hasUnreadCount;
- (UInt32) unreadCount;
- (ServerUnReadInfoBuilder*) setUnreadCount:(UInt32) value;
- (ServerUnReadInfoBuilder*) clearUnreadCount;
@end

@interface ClientMsgInfo : PBGeneratedMessage {
@private
  BOOL hasFromUserId_:1;
  BOOL hasFromUserName_:1;
  BOOL hasFromUserNickName_:1;
  BOOL hasFromUserAvatarUrl_:1;
  BOOL hasMsgContent_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  NSString* fromUserId;
  NSString* fromUserName;
  NSString* fromUserNickName;
  NSString* fromUserAvatarUrl;
  NSString* msgContent;
  UInt32 createTime;
  UInt32 msgType;
}
- (BOOL) hasFromUserId;
- (BOOL) hasFromUserName;
- (BOOL) hasFromUserNickName;
- (BOOL) hasFromUserAvatarUrl;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgContent;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* fromUserName;
@property (readonly, strong) NSString* fromUserNickName;
@property (readonly, strong) NSString* fromUserAvatarUrl;
@property (readonly) UInt32 createTime;
@property (readonly) UInt32 msgType;
@property (readonly, strong) NSString* msgContent;

+ (ClientMsgInfo*) defaultInstance;
- (ClientMsgInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientMsgInfoBuilder*) builder;
+ (ClientMsgInfoBuilder*) builder;
+ (ClientMsgInfoBuilder*) builderWithPrototype:(ClientMsgInfo*) prototype;
- (ClientMsgInfoBuilder*) toBuilder;

+ (ClientMsgInfo*) parseFromData:(NSData*) data;
+ (ClientMsgInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientMsgInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientMsgInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClientMsgInfo* result;
}

- (ClientMsgInfo*) defaultInstance;

- (ClientMsgInfoBuilder*) clear;
- (ClientMsgInfoBuilder*) clone;

- (ClientMsgInfo*) build;
- (ClientMsgInfo*) buildPartial;

- (ClientMsgInfoBuilder*) mergeFrom:(ClientMsgInfo*) other;
- (ClientMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientMsgInfoBuilder*) setFromUserId:(NSString*) value;
- (ClientMsgInfoBuilder*) clearFromUserId;

- (BOOL) hasFromUserName;
- (NSString*) fromUserName;
- (ClientMsgInfoBuilder*) setFromUserName:(NSString*) value;
- (ClientMsgInfoBuilder*) clearFromUserName;

- (BOOL) hasFromUserNickName;
- (NSString*) fromUserNickName;
- (ClientMsgInfoBuilder*) setFromUserNickName:(NSString*) value;
- (ClientMsgInfoBuilder*) clearFromUserNickName;

- (BOOL) hasFromUserAvatarUrl;
- (NSString*) fromUserAvatarUrl;
- (ClientMsgInfoBuilder*) setFromUserAvatarUrl:(NSString*) value;
- (ClientMsgInfoBuilder*) clearFromUserAvatarUrl;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (ClientMsgInfoBuilder*) setCreateTime:(UInt32) value;
- (ClientMsgInfoBuilder*) clearCreateTime;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (ClientMsgInfoBuilder*) setMsgType:(UInt32) value;
- (ClientMsgInfoBuilder*) clearMsgType;

- (BOOL) hasMsgContent;
- (NSString*) msgContent;
- (ClientMsgInfoBuilder*) setMsgContent:(NSString*) value;
- (ClientMsgInfoBuilder*) clearMsgContent;
@end

@interface ServerMsgInfo : PBGeneratedMessage {
@private
  BOOL hasFromUserName_:1;
  BOOL hasFromUserNickName_:1;
  BOOL hasFromUserAvatarUrl_:1;
  BOOL hasMsgContent_:1;
  BOOL hasFromUserId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  NSString* fromUserName;
  NSString* fromUserNickName;
  NSString* fromUserAvatarUrl;
  NSString* msgContent;
  UInt32 fromUserId;
  UInt32 createTime;
  UInt32 msgType;
}
- (BOOL) hasFromUserId;
- (BOOL) hasFromUserName;
- (BOOL) hasFromUserNickName;
- (BOOL) hasFromUserAvatarUrl;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgContent;
@property (readonly) UInt32 fromUserId;
@property (readonly, strong) NSString* fromUserName;
@property (readonly, strong) NSString* fromUserNickName;
@property (readonly, strong) NSString* fromUserAvatarUrl;
@property (readonly) UInt32 createTime;
@property (readonly) UInt32 msgType;
@property (readonly, strong) NSString* msgContent;

+ (ServerMsgInfo*) defaultInstance;
- (ServerMsgInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerMsgInfoBuilder*) builder;
+ (ServerMsgInfoBuilder*) builder;
+ (ServerMsgInfoBuilder*) builderWithPrototype:(ServerMsgInfo*) prototype;
- (ServerMsgInfoBuilder*) toBuilder;

+ (ServerMsgInfo*) parseFromData:(NSData*) data;
+ (ServerMsgInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerMsgInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ServerMsgInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerMsgInfoBuilder : PBGeneratedMessageBuilder {
@private
  ServerMsgInfo* result;
}

- (ServerMsgInfo*) defaultInstance;

- (ServerMsgInfoBuilder*) clear;
- (ServerMsgInfoBuilder*) clone;

- (ServerMsgInfo*) build;
- (ServerMsgInfo*) buildPartial;

- (ServerMsgInfoBuilder*) mergeFrom:(ServerMsgInfo*) other;
- (ServerMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (ServerMsgInfoBuilder*) setFromUserId:(UInt32) value;
- (ServerMsgInfoBuilder*) clearFromUserId;

- (BOOL) hasFromUserName;
- (NSString*) fromUserName;
- (ServerMsgInfoBuilder*) setFromUserName:(NSString*) value;
- (ServerMsgInfoBuilder*) clearFromUserName;

- (BOOL) hasFromUserNickName;
- (NSString*) fromUserNickName;
- (ServerMsgInfoBuilder*) setFromUserNickName:(NSString*) value;
- (ServerMsgInfoBuilder*) clearFromUserNickName;

- (BOOL) hasFromUserAvatarUrl;
- (NSString*) fromUserAvatarUrl;
- (ServerMsgInfoBuilder*) setFromUserAvatarUrl:(NSString*) value;
- (ServerMsgInfoBuilder*) clearFromUserAvatarUrl;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (ServerMsgInfoBuilder*) setCreateTime:(UInt32) value;
- (ServerMsgInfoBuilder*) clearCreateTime;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (ServerMsgInfoBuilder*) setMsgType:(UInt32) value;
- (ServerMsgInfoBuilder*) clearMsgType;

- (BOOL) hasMsgContent;
- (NSString*) msgContent;
- (ServerMsgInfoBuilder*) setMsgContent:(NSString*) value;
- (ServerMsgInfoBuilder*) clearMsgContent;
@end

@interface ClientGroupInfo : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasGroupCreatorId_:1;
  BOOL hasGroupUpdated_:1;
  BOOL hasGroupType_:1;
  NSString* groupId;
  NSString* groupName;
  NSString* groupAvatar;
  NSString* groupCreatorId;
  UInt32 groupUpdated;
  GroupType groupType;
  NSMutableArray * groupMemberListArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasGroupCreatorId;
- (BOOL) hasGroupType;
- (BOOL) hasGroupUpdated;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly, strong) NSString* groupCreatorId;
@property (readonly) GroupType groupType;
@property (readonly) UInt32 groupUpdated;
@property (readonly, strong) PBArray * groupMemberList;
- (NSString*)groupMemberListAtIndex:(NSUInteger)index;

+ (ClientGroupInfo*) defaultInstance;
- (ClientGroupInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientGroupInfoBuilder*) builder;
+ (ClientGroupInfoBuilder*) builder;
+ (ClientGroupInfoBuilder*) builderWithPrototype:(ClientGroupInfo*) prototype;
- (ClientGroupInfoBuilder*) toBuilder;

+ (ClientGroupInfo*) parseFromData:(NSData*) data;
+ (ClientGroupInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientGroupInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientGroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientGroupInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClientGroupInfo* result;
}

- (ClientGroupInfo*) defaultInstance;

- (ClientGroupInfoBuilder*) clear;
- (ClientGroupInfoBuilder*) clone;

- (ClientGroupInfo*) build;
- (ClientGroupInfo*) buildPartial;

- (ClientGroupInfoBuilder*) mergeFrom:(ClientGroupInfo*) other;
- (ClientGroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientGroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (ClientGroupInfoBuilder*) setGroupId:(NSString*) value;
- (ClientGroupInfoBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (ClientGroupInfoBuilder*) setGroupName:(NSString*) value;
- (ClientGroupInfoBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (ClientGroupInfoBuilder*) setGroupAvatar:(NSString*) value;
- (ClientGroupInfoBuilder*) clearGroupAvatar;

- (BOOL) hasGroupCreatorId;
- (NSString*) groupCreatorId;
- (ClientGroupInfoBuilder*) setGroupCreatorId:(NSString*) value;
- (ClientGroupInfoBuilder*) clearGroupCreatorId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (ClientGroupInfoBuilder*) setGroupType:(GroupType) value;
- (ClientGroupInfoBuilder*) clearGroupType;

- (BOOL) hasGroupUpdated;
- (UInt32) groupUpdated;
- (ClientGroupInfoBuilder*) setGroupUpdated:(UInt32) value;
- (ClientGroupInfoBuilder*) clearGroupUpdated;

- (NSMutableArray *)groupMemberList;
- (NSString*)groupMemberListAtIndex:(NSUInteger)index;
- (ClientGroupInfoBuilder *)addGroupMemberList:(NSString*)value;
- (ClientGroupInfoBuilder *)setGroupMemberListArray:(NSArray *)array;
- (ClientGroupInfoBuilder *)clearGroupMemberList;
@end

@interface ServerGroupInfo : PBGeneratedMessage {
@private
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasGroupId_:1;
  BOOL hasGroupCreatorId_:1;
  BOOL hasGroupUpdated_:1;
  BOOL hasGroupType_:1;
  NSString* groupName;
  NSString* groupAvatar;
  UInt32 groupId;
  UInt32 groupCreatorId;
  UInt32 groupUpdated;
  GroupType groupType;
  PBAppendableArray * groupMemberListArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasGroupCreatorId;
- (BOOL) hasGroupType;
- (BOOL) hasGroupUpdated;
@property (readonly) UInt32 groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly) UInt32 groupCreatorId;
@property (readonly) GroupType groupType;
@property (readonly) UInt32 groupUpdated;
@property (readonly, strong) PBArray * groupMemberList;
- (UInt32)groupMemberListAtIndex:(NSUInteger)index;

+ (ServerGroupInfo*) defaultInstance;
- (ServerGroupInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerGroupInfoBuilder*) builder;
+ (ServerGroupInfoBuilder*) builder;
+ (ServerGroupInfoBuilder*) builderWithPrototype:(ServerGroupInfo*) prototype;
- (ServerGroupInfoBuilder*) toBuilder;

+ (ServerGroupInfo*) parseFromData:(NSData*) data;
+ (ServerGroupInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ServerGroupInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerGroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerGroupInfoBuilder : PBGeneratedMessageBuilder {
@private
  ServerGroupInfo* result;
}

- (ServerGroupInfo*) defaultInstance;

- (ServerGroupInfoBuilder*) clear;
- (ServerGroupInfoBuilder*) clone;

- (ServerGroupInfo*) build;
- (ServerGroupInfo*) buildPartial;

- (ServerGroupInfoBuilder*) mergeFrom:(ServerGroupInfo*) other;
- (ServerGroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerGroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (ServerGroupInfoBuilder*) setGroupId:(UInt32) value;
- (ServerGroupInfoBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (ServerGroupInfoBuilder*) setGroupName:(NSString*) value;
- (ServerGroupInfoBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (ServerGroupInfoBuilder*) setGroupAvatar:(NSString*) value;
- (ServerGroupInfoBuilder*) clearGroupAvatar;

- (BOOL) hasGroupCreatorId;
- (UInt32) groupCreatorId;
- (ServerGroupInfoBuilder*) setGroupCreatorId:(UInt32) value;
- (ServerGroupInfoBuilder*) clearGroupCreatorId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (ServerGroupInfoBuilder*) setGroupType:(GroupType) value;
- (ServerGroupInfoBuilder*) clearGroupType;

- (BOOL) hasGroupUpdated;
- (UInt32) groupUpdated;
- (ServerGroupInfoBuilder*) setGroupUpdated:(UInt32) value;
- (ServerGroupInfoBuilder*) clearGroupUpdated;

- (PBAppendableArray *)groupMemberList;
- (UInt32)groupMemberListAtIndex:(NSUInteger)index;
- (ServerGroupInfoBuilder *)addGroupMemberList:(UInt32)value;
- (ServerGroupInfoBuilder *)setGroupMemberListArray:(NSArray *)array;
- (ServerGroupInfoBuilder *)setGroupMemberListValues:(const UInt32 *)values count:(NSUInteger)count;
- (ServerGroupInfoBuilder *)clearGroupMemberList;
@end

@interface ClientGroupUnReadCnt : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasUnreadCnt_:1;
  NSString* groupId;
  UInt32 unreadCnt;
}
- (BOOL) hasGroupId;
- (BOOL) hasUnreadCnt;
@property (readonly, strong) NSString* groupId;
@property (readonly) UInt32 unreadCnt;

+ (ClientGroupUnReadCnt*) defaultInstance;
- (ClientGroupUnReadCnt*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientGroupUnReadCntBuilder*) builder;
+ (ClientGroupUnReadCntBuilder*) builder;
+ (ClientGroupUnReadCntBuilder*) builderWithPrototype:(ClientGroupUnReadCnt*) prototype;
- (ClientGroupUnReadCntBuilder*) toBuilder;

+ (ClientGroupUnReadCnt*) parseFromData:(NSData*) data;
+ (ClientGroupUnReadCnt*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupUnReadCnt*) parseFromInputStream:(NSInputStream*) input;
+ (ClientGroupUnReadCnt*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupUnReadCnt*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientGroupUnReadCnt*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientGroupUnReadCntBuilder : PBGeneratedMessageBuilder {
@private
  ClientGroupUnReadCnt* result;
}

- (ClientGroupUnReadCnt*) defaultInstance;

- (ClientGroupUnReadCntBuilder*) clear;
- (ClientGroupUnReadCntBuilder*) clone;

- (ClientGroupUnReadCnt*) build;
- (ClientGroupUnReadCnt*) buildPartial;

- (ClientGroupUnReadCntBuilder*) mergeFrom:(ClientGroupUnReadCnt*) other;
- (ClientGroupUnReadCntBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientGroupUnReadCntBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (ClientGroupUnReadCntBuilder*) setGroupId:(NSString*) value;
- (ClientGroupUnReadCntBuilder*) clearGroupId;

- (BOOL) hasUnreadCnt;
- (UInt32) unreadCnt;
- (ClientGroupUnReadCntBuilder*) setUnreadCnt:(UInt32) value;
- (ClientGroupUnReadCntBuilder*) clearUnreadCnt;
@end

@interface ServerGroupUnReadCnt : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasUnreadCnt_:1;
  UInt32 groupId;
  UInt32 unreadCnt;
}
- (BOOL) hasGroupId;
- (BOOL) hasUnreadCnt;
@property (readonly) UInt32 groupId;
@property (readonly) UInt32 unreadCnt;

+ (ServerGroupUnReadCnt*) defaultInstance;
- (ServerGroupUnReadCnt*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerGroupUnReadCntBuilder*) builder;
+ (ServerGroupUnReadCntBuilder*) builder;
+ (ServerGroupUnReadCntBuilder*) builderWithPrototype:(ServerGroupUnReadCnt*) prototype;
- (ServerGroupUnReadCntBuilder*) toBuilder;

+ (ServerGroupUnReadCnt*) parseFromData:(NSData*) data;
+ (ServerGroupUnReadCnt*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupUnReadCnt*) parseFromInputStream:(NSInputStream*) input;
+ (ServerGroupUnReadCnt*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupUnReadCnt*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerGroupUnReadCnt*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerGroupUnReadCntBuilder : PBGeneratedMessageBuilder {
@private
  ServerGroupUnReadCnt* result;
}

- (ServerGroupUnReadCnt*) defaultInstance;

- (ServerGroupUnReadCntBuilder*) clear;
- (ServerGroupUnReadCntBuilder*) clone;

- (ServerGroupUnReadCnt*) build;
- (ServerGroupUnReadCnt*) buildPartial;

- (ServerGroupUnReadCntBuilder*) mergeFrom:(ServerGroupUnReadCnt*) other;
- (ServerGroupUnReadCntBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerGroupUnReadCntBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (ServerGroupUnReadCntBuilder*) setGroupId:(UInt32) value;
- (ServerGroupUnReadCntBuilder*) clearGroupId;

- (BOOL) hasUnreadCnt;
- (UInt32) unreadCnt;
- (ServerGroupUnReadCntBuilder*) setUnreadCnt:(UInt32) value;
- (ServerGroupUnReadCntBuilder*) clearUnreadCnt;
@end

@interface ClientGroupMsg : PBGeneratedMessage {
@private
  BOOL hasFromUserId_:1;
  BOOL hasMsgContent_:1;
  BOOL hasCreateTime_:1;
  NSString* fromUserId;
  NSString* msgContent;
  UInt32 createTime;
}
- (BOOL) hasFromUserId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgContent;
@property (readonly, strong) NSString* fromUserId;
@property (readonly) UInt32 createTime;
@property (readonly, strong) NSString* msgContent;

+ (ClientGroupMsg*) defaultInstance;
- (ClientGroupMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientGroupMsgBuilder*) builder;
+ (ClientGroupMsgBuilder*) builder;
+ (ClientGroupMsgBuilder*) builderWithPrototype:(ClientGroupMsg*) prototype;
- (ClientGroupMsgBuilder*) toBuilder;

+ (ClientGroupMsg*) parseFromData:(NSData*) data;
+ (ClientGroupMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupMsg*) parseFromInputStream:(NSInputStream*) input;
+ (ClientGroupMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientGroupMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientGroupMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientGroupMsgBuilder : PBGeneratedMessageBuilder {
@private
  ClientGroupMsg* result;
}

- (ClientGroupMsg*) defaultInstance;

- (ClientGroupMsgBuilder*) clear;
- (ClientGroupMsgBuilder*) clone;

- (ClientGroupMsg*) build;
- (ClientGroupMsg*) buildPartial;

- (ClientGroupMsgBuilder*) mergeFrom:(ClientGroupMsg*) other;
- (ClientGroupMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientGroupMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientGroupMsgBuilder*) setFromUserId:(NSString*) value;
- (ClientGroupMsgBuilder*) clearFromUserId;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (ClientGroupMsgBuilder*) setCreateTime:(UInt32) value;
- (ClientGroupMsgBuilder*) clearCreateTime;

- (BOOL) hasMsgContent;
- (NSString*) msgContent;
- (ClientGroupMsgBuilder*) setMsgContent:(NSString*) value;
- (ClientGroupMsgBuilder*) clearMsgContent;
@end

@interface ServerGroupMsg : PBGeneratedMessage {
@private
  BOOL hasMsgContent_:1;
  BOOL hasFromUserId_:1;
  BOOL hasCreateTime_:1;
  NSString* msgContent;
  UInt32 fromUserId;
  UInt32 createTime;
}
- (BOOL) hasFromUserId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgContent;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 createTime;
@property (readonly, strong) NSString* msgContent;

+ (ServerGroupMsg*) defaultInstance;
- (ServerGroupMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerGroupMsgBuilder*) builder;
+ (ServerGroupMsgBuilder*) builder;
+ (ServerGroupMsgBuilder*) builderWithPrototype:(ServerGroupMsg*) prototype;
- (ServerGroupMsgBuilder*) toBuilder;

+ (ServerGroupMsg*) parseFromData:(NSData*) data;
+ (ServerGroupMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupMsg*) parseFromInputStream:(NSInputStream*) input;
+ (ServerGroupMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerGroupMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerGroupMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerGroupMsgBuilder : PBGeneratedMessageBuilder {
@private
  ServerGroupMsg* result;
}

- (ServerGroupMsg*) defaultInstance;

- (ServerGroupMsgBuilder*) clear;
- (ServerGroupMsgBuilder*) clone;

- (ServerGroupMsg*) build;
- (ServerGroupMsg*) buildPartial;

- (ServerGroupMsgBuilder*) mergeFrom:(ServerGroupMsg*) other;
- (ServerGroupMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerGroupMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (ServerGroupMsgBuilder*) setFromUserId:(UInt32) value;
- (ServerGroupMsgBuilder*) clearFromUserId;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (ServerGroupMsgBuilder*) setCreateTime:(UInt32) value;
- (ServerGroupMsgBuilder*) clearCreateTime;

- (BOOL) hasMsgContent;
- (NSString*) msgContent;
- (ServerGroupMsgBuilder*) setMsgContent:(NSString*) value;
- (ServerGroupMsgBuilder*) clearMsgContent;
@end

@interface ClientOfflineFileInfo : PBGeneratedMessage {
@private
  BOOL hasFromUserId_:1;
  BOOL hasFilePath_:1;
  BOOL hasFileId_:1;
  BOOL hasFileSize_:1;
  NSString* fromUserId;
  NSString* filePath;
  UInt32 fileId;
  UInt32 fileSize;
}
- (BOOL) hasFromUserId;
- (BOOL) hasFileId;
- (BOOL) hasFileSize;
- (BOOL) hasFilePath;
@property (readonly, strong) NSString* fromUserId;
@property (readonly) UInt32 fileId;
@property (readonly) UInt32 fileSize;
@property (readonly, strong) NSString* filePath;

+ (ClientOfflineFileInfo*) defaultInstance;
- (ClientOfflineFileInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientOfflineFileInfoBuilder*) builder;
+ (ClientOfflineFileInfoBuilder*) builder;
+ (ClientOfflineFileInfoBuilder*) builderWithPrototype:(ClientOfflineFileInfo*) prototype;
- (ClientOfflineFileInfoBuilder*) toBuilder;

+ (ClientOfflineFileInfo*) parseFromData:(NSData*) data;
+ (ClientOfflineFileInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientOfflineFileInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientOfflineFileInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientOfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientOfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientOfflineFileInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClientOfflineFileInfo* result;
}

- (ClientOfflineFileInfo*) defaultInstance;

- (ClientOfflineFileInfoBuilder*) clear;
- (ClientOfflineFileInfoBuilder*) clone;

- (ClientOfflineFileInfo*) build;
- (ClientOfflineFileInfo*) buildPartial;

- (ClientOfflineFileInfoBuilder*) mergeFrom:(ClientOfflineFileInfo*) other;
- (ClientOfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientOfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientOfflineFileInfoBuilder*) setFromUserId:(NSString*) value;
- (ClientOfflineFileInfoBuilder*) clearFromUserId;

- (BOOL) hasFileId;
- (UInt32) fileId;
- (ClientOfflineFileInfoBuilder*) setFileId:(UInt32) value;
- (ClientOfflineFileInfoBuilder*) clearFileId;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (ClientOfflineFileInfoBuilder*) setFileSize:(UInt32) value;
- (ClientOfflineFileInfoBuilder*) clearFileSize;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (ClientOfflineFileInfoBuilder*) setFilePath:(NSString*) value;
- (ClientOfflineFileInfoBuilder*) clearFilePath;
@end

@interface ServerOfflineFileInfo : PBGeneratedMessage {
@private
  BOOL hasFilePath_:1;
  BOOL hasFromUserId_:1;
  BOOL hasFileId_:1;
  BOOL hasFileSize_:1;
  NSString* filePath;
  UInt32 fromUserId;
  UInt32 fileId;
  UInt32 fileSize;
}
- (BOOL) hasFromUserId;
- (BOOL) hasFileId;
- (BOOL) hasFileSize;
- (BOOL) hasFilePath;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 fileId;
@property (readonly) UInt32 fileSize;
@property (readonly, strong) NSString* filePath;

+ (ServerOfflineFileInfo*) defaultInstance;
- (ServerOfflineFileInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerOfflineFileInfoBuilder*) builder;
+ (ServerOfflineFileInfoBuilder*) builder;
+ (ServerOfflineFileInfoBuilder*) builderWithPrototype:(ServerOfflineFileInfo*) prototype;
- (ServerOfflineFileInfoBuilder*) toBuilder;

+ (ServerOfflineFileInfo*) parseFromData:(NSData*) data;
+ (ServerOfflineFileInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerOfflineFileInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ServerOfflineFileInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerOfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerOfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerOfflineFileInfoBuilder : PBGeneratedMessageBuilder {
@private
  ServerOfflineFileInfo* result;
}

- (ServerOfflineFileInfo*) defaultInstance;

- (ServerOfflineFileInfoBuilder*) clear;
- (ServerOfflineFileInfoBuilder*) clone;

- (ServerOfflineFileInfo*) build;
- (ServerOfflineFileInfo*) buildPartial;

- (ServerOfflineFileInfoBuilder*) mergeFrom:(ServerOfflineFileInfo*) other;
- (ServerOfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerOfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (ServerOfflineFileInfoBuilder*) setFromUserId:(UInt32) value;
- (ServerOfflineFileInfoBuilder*) clearFromUserId;

- (BOOL) hasFileId;
- (UInt32) fileId;
- (ServerOfflineFileInfoBuilder*) setFileId:(UInt32) value;
- (ServerOfflineFileInfoBuilder*) clearFileId;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (ServerOfflineFileInfoBuilder*) setFileSize:(UInt32) value;
- (ServerOfflineFileInfoBuilder*) clearFileSize;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (ServerOfflineFileInfoBuilder*) setFilePath:(NSString*) value;
- (ServerOfflineFileInfoBuilder*) clearFilePath;
@end


// @@protoc_insertion_point(global_scope)
