// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class C2MGroupChangeMemberReq;
@class C2MGroupChangeMemberReqBuilder;
@class C2MGroupChangeMemberRsp;
@class C2MGroupChangeMemberRspBuilder;
@class C2MGroupCreateTmpGroupReq;
@class C2MGroupCreateTmpGroupReqBuilder;
@class C2MGroupCreateTmpGroupRsp;
@class C2MGroupCreateTmpGroupRspBuilder;
@class C2MGroupHistoryMsgReq;
@class C2MGroupHistoryMsgReqBuilder;
@class C2MGroupListReq;
@class C2MGroupListReqBuilder;
@class C2MGroupListRsp;
@class C2MGroupListRspBuilder;
@class C2MGroupMsgListRsp;
@class C2MGroupMsgListRspBuilder;
@class C2MGroupMsgReadAck;
@class C2MGroupMsgReadAckBuilder;
@class C2MGroupUnReadMsgCntReq;
@class C2MGroupUnReadMsgCntReqBuilder;
@class C2MGroupUnReadMsgCntRsp;
@class C2MGroupUnReadMsgCntRspBuilder;
@class C2MGroupUnReadMsgReq;
@class C2MGroupUnReadMsgReqBuilder;
@class C2MGroupUserListReq;
@class C2MGroupUserListReqBuilder;
@class C2MGroupUserListRsp;
@class C2MGroupUserListRspBuilder;
@class ClientGroupInfo;
@class ClientGroupInfoBuilder;
@class ClientGroupMsg;
@class ClientGroupMsgBuilder;
@class ClientGroupUnReadCnt;
@class ClientGroupUnReadCntBuilder;
@class ClientMsgInfo;
@class ClientMsgInfoBuilder;
@class ClientOfflineFileInfo;
@class ClientOfflineFileInfoBuilder;
@class ClientUnReadInfo;
@class ClientUnReadInfoBuilder;
@class ClientUserInfo;
@class ClientUserInfoBuilder;
@class ClientUserStat;
@class ClientUserStatBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class ServerGroupInfo;
@class ServerGroupInfoBuilder;
@class ServerGroupMsg;
@class ServerGroupMsgBuilder;
@class ServerGroupUnReadCnt;
@class ServerGroupUnReadCntBuilder;
@class ServerMsgInfo;
@class ServerMsgInfoBuilder;
@class ServerOfflineFileInfo;
@class ServerOfflineFileInfoBuilder;
@class ServerUnReadInfo;
@class ServerUnReadInfoBuilder;
@class ServerUserInfo;
@class ServerUserInfoBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface Imclient2ServGroupRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface C2MGroupListReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MGroupListReq*) defaultInstance;
- (C2MGroupListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupListReqBuilder*) builder;
+ (C2MGroupListReqBuilder*) builder;
+ (C2MGroupListReqBuilder*) builderWithPrototype:(C2MGroupListReq*) prototype;
- (C2MGroupListReqBuilder*) toBuilder;

+ (C2MGroupListReq*) parseFromData:(NSData*) data;
+ (C2MGroupListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupListReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupListReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupListReq* result;
}

- (C2MGroupListReq*) defaultInstance;

- (C2MGroupListReqBuilder*) clear;
- (C2MGroupListReqBuilder*) clone;

- (C2MGroupListReq*) build;
- (C2MGroupListReq*) buildPartial;

- (C2MGroupListReqBuilder*) mergeFrom:(C2MGroupListReq*) other;
- (C2MGroupListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupListReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupListReqBuilder*) clearCmdId;
@end

@interface C2MGroupListRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * groupInfoListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * groupInfoList;
- (ClientGroupInfo*)groupInfoListAtIndex:(NSUInteger)index;

+ (C2MGroupListRsp*) defaultInstance;
- (C2MGroupListRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupListRspBuilder*) builder;
+ (C2MGroupListRspBuilder*) builder;
+ (C2MGroupListRspBuilder*) builderWithPrototype:(C2MGroupListRsp*) prototype;
- (C2MGroupListRspBuilder*) toBuilder;

+ (C2MGroupListRsp*) parseFromData:(NSData*) data;
+ (C2MGroupListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupListRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupListRsp* result;
}

- (C2MGroupListRsp*) defaultInstance;

- (C2MGroupListRspBuilder*) clear;
- (C2MGroupListRspBuilder*) clone;

- (C2MGroupListRsp*) build;
- (C2MGroupListRsp*) buildPartial;

- (C2MGroupListRspBuilder*) mergeFrom:(C2MGroupListRsp*) other;
- (C2MGroupListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupListRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupListRspBuilder*) clearCmdId;

- (NSMutableArray *)groupInfoList;
- (ClientGroupInfo*)groupInfoListAtIndex:(NSUInteger)index;
- (C2MGroupListRspBuilder *)addGroupInfoList:(ClientGroupInfo*)value;
- (C2MGroupListRspBuilder *)setGroupInfoListArray:(NSArray *)array;
- (C2MGroupListRspBuilder *)clearGroupInfoList;
@end

@interface C2MGroupUserListReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  SInt32 cmdId;
  NSString* groupId;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupId;

+ (C2MGroupUserListReq*) defaultInstance;
- (C2MGroupUserListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupUserListReqBuilder*) builder;
+ (C2MGroupUserListReqBuilder*) builder;
+ (C2MGroupUserListReqBuilder*) builderWithPrototype:(C2MGroupUserListReq*) prototype;
- (C2MGroupUserListReqBuilder*) toBuilder;

+ (C2MGroupUserListReq*) parseFromData:(NSData*) data;
+ (C2MGroupUserListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUserListReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupUserListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUserListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupUserListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupUserListReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupUserListReq* result;
}

- (C2MGroupUserListReq*) defaultInstance;

- (C2MGroupUserListReqBuilder*) clear;
- (C2MGroupUserListReqBuilder*) clone;

- (C2MGroupUserListReq*) build;
- (C2MGroupUserListReq*) buildPartial;

- (C2MGroupUserListReqBuilder*) mergeFrom:(C2MGroupUserListReq*) other;
- (C2MGroupUserListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupUserListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupUserListReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupUserListReqBuilder*) clearCmdId;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupUserListReqBuilder*) setGroupId:(NSString*) value;
- (C2MGroupUserListReqBuilder*) clearGroupId;
@end

@interface C2MGroupUserListRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasGroupCreatorId_:1;
  BOOL hasResults_:1;
  BOOL hasGroupType_:1;
  SInt32 cmdId;
  NSString* groupId;
  NSString* groupName;
  NSString* groupAvatar;
  NSString* groupCreatorId;
  UInt32 results;
  GroupType groupType;
  NSMutableArray * groupMemberListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasGroupCreatorId;
- (BOOL) hasGroupType;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 results;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly, strong) NSString* groupCreatorId;
@property (readonly) GroupType groupType;
@property (readonly, strong) PBArray * groupMemberList;
- (NSString*)groupMemberListAtIndex:(NSUInteger)index;

+ (C2MGroupUserListRsp*) defaultInstance;
- (C2MGroupUserListRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupUserListRspBuilder*) builder;
+ (C2MGroupUserListRspBuilder*) builder;
+ (C2MGroupUserListRspBuilder*) builderWithPrototype:(C2MGroupUserListRsp*) prototype;
- (C2MGroupUserListRspBuilder*) toBuilder;

+ (C2MGroupUserListRsp*) parseFromData:(NSData*) data;
+ (C2MGroupUserListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUserListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupUserListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUserListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupUserListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupUserListRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupUserListRsp* result;
}

- (C2MGroupUserListRsp*) defaultInstance;

- (C2MGroupUserListRspBuilder*) clear;
- (C2MGroupUserListRspBuilder*) clone;

- (C2MGroupUserListRsp*) build;
- (C2MGroupUserListRsp*) buildPartial;

- (C2MGroupUserListRspBuilder*) mergeFrom:(C2MGroupUserListRsp*) other;
- (C2MGroupUserListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupUserListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupUserListRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupUserListRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (UInt32) results;
- (C2MGroupUserListRspBuilder*) setResults:(UInt32) value;
- (C2MGroupUserListRspBuilder*) clearResults;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupUserListRspBuilder*) setGroupId:(NSString*) value;
- (C2MGroupUserListRspBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (C2MGroupUserListRspBuilder*) setGroupName:(NSString*) value;
- (C2MGroupUserListRspBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (C2MGroupUserListRspBuilder*) setGroupAvatar:(NSString*) value;
- (C2MGroupUserListRspBuilder*) clearGroupAvatar;

- (BOOL) hasGroupCreatorId;
- (NSString*) groupCreatorId;
- (C2MGroupUserListRspBuilder*) setGroupCreatorId:(NSString*) value;
- (C2MGroupUserListRspBuilder*) clearGroupCreatorId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (C2MGroupUserListRspBuilder*) setGroupType:(GroupType) value;
- (C2MGroupUserListRspBuilder*) clearGroupType;

- (NSMutableArray *)groupMemberList;
- (NSString*)groupMemberListAtIndex:(NSUInteger)index;
- (C2MGroupUserListRspBuilder *)addGroupMemberList:(NSString*)value;
- (C2MGroupUserListRspBuilder *)setGroupMemberListArray:(NSArray *)array;
- (C2MGroupUserListRspBuilder *)clearGroupMemberList;
@end

@interface C2MGroupUnReadMsgCntReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MGroupUnReadMsgCntReq*) defaultInstance;
- (C2MGroupUnReadMsgCntReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupUnReadMsgCntReqBuilder*) builder;
+ (C2MGroupUnReadMsgCntReqBuilder*) builder;
+ (C2MGroupUnReadMsgCntReqBuilder*) builderWithPrototype:(C2MGroupUnReadMsgCntReq*) prototype;
- (C2MGroupUnReadMsgCntReqBuilder*) toBuilder;

+ (C2MGroupUnReadMsgCntReq*) parseFromData:(NSData*) data;
+ (C2MGroupUnReadMsgCntReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgCntReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupUnReadMsgCntReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupUnReadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupUnReadMsgCntReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupUnReadMsgCntReq* result;
}

- (C2MGroupUnReadMsgCntReq*) defaultInstance;

- (C2MGroupUnReadMsgCntReqBuilder*) clear;
- (C2MGroupUnReadMsgCntReqBuilder*) clone;

- (C2MGroupUnReadMsgCntReq*) build;
- (C2MGroupUnReadMsgCntReq*) buildPartial;

- (C2MGroupUnReadMsgCntReqBuilder*) mergeFrom:(C2MGroupUnReadMsgCntReq*) other;
- (C2MGroupUnReadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupUnReadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupUnReadMsgCntReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupUnReadMsgCntReqBuilder*) clearCmdId;
@end

@interface C2MGroupUnReadMsgCntRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * groupUnreadMsgCntArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * groupUnreadMsgCnt;
- (ClientGroupUnReadCnt*)groupUnreadMsgCntAtIndex:(NSUInteger)index;

+ (C2MGroupUnReadMsgCntRsp*) defaultInstance;
- (C2MGroupUnReadMsgCntRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupUnReadMsgCntRspBuilder*) builder;
+ (C2MGroupUnReadMsgCntRspBuilder*) builder;
+ (C2MGroupUnReadMsgCntRspBuilder*) builderWithPrototype:(C2MGroupUnReadMsgCntRsp*) prototype;
- (C2MGroupUnReadMsgCntRspBuilder*) toBuilder;

+ (C2MGroupUnReadMsgCntRsp*) parseFromData:(NSData*) data;
+ (C2MGroupUnReadMsgCntRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupUnReadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupUnReadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupUnReadMsgCntRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupUnReadMsgCntRsp* result;
}

- (C2MGroupUnReadMsgCntRsp*) defaultInstance;

- (C2MGroupUnReadMsgCntRspBuilder*) clear;
- (C2MGroupUnReadMsgCntRspBuilder*) clone;

- (C2MGroupUnReadMsgCntRsp*) build;
- (C2MGroupUnReadMsgCntRsp*) buildPartial;

- (C2MGroupUnReadMsgCntRspBuilder*) mergeFrom:(C2MGroupUnReadMsgCntRsp*) other;
- (C2MGroupUnReadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupUnReadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupUnReadMsgCntRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupUnReadMsgCntRspBuilder*) clearCmdId;

- (NSMutableArray *)groupUnreadMsgCnt;
- (ClientGroupUnReadCnt*)groupUnreadMsgCntAtIndex:(NSUInteger)index;
- (C2MGroupUnReadMsgCntRspBuilder *)addGroupUnreadMsgCnt:(ClientGroupUnReadCnt*)value;
- (C2MGroupUnReadMsgCntRspBuilder *)setGroupUnreadMsgCntArray:(NSArray *)array;
- (C2MGroupUnReadMsgCntRspBuilder *)clearGroupUnreadMsgCnt;
@end

@interface C2MGroupUnReadMsgReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  SInt32 cmdId;
  NSString* groupId;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupId;

+ (C2MGroupUnReadMsgReq*) defaultInstance;
- (C2MGroupUnReadMsgReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupUnReadMsgReqBuilder*) builder;
+ (C2MGroupUnReadMsgReqBuilder*) builder;
+ (C2MGroupUnReadMsgReqBuilder*) builderWithPrototype:(C2MGroupUnReadMsgReq*) prototype;
- (C2MGroupUnReadMsgReqBuilder*) toBuilder;

+ (C2MGroupUnReadMsgReq*) parseFromData:(NSData*) data;
+ (C2MGroupUnReadMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupUnReadMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupUnReadMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupUnReadMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupUnReadMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupUnReadMsgReq* result;
}

- (C2MGroupUnReadMsgReq*) defaultInstance;

- (C2MGroupUnReadMsgReqBuilder*) clear;
- (C2MGroupUnReadMsgReqBuilder*) clone;

- (C2MGroupUnReadMsgReq*) build;
- (C2MGroupUnReadMsgReq*) buildPartial;

- (C2MGroupUnReadMsgReqBuilder*) mergeFrom:(C2MGroupUnReadMsgReq*) other;
- (C2MGroupUnReadMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupUnReadMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupUnReadMsgReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupUnReadMsgReqBuilder*) clearCmdId;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupUnReadMsgReqBuilder*) setGroupId:(NSString*) value;
- (C2MGroupUnReadMsgReqBuilder*) clearGroupId;
@end

@interface C2MGroupHistoryMsgReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  BOOL hasMsgOffset_:1;
  BOOL hasMsgCount_:1;
  SInt32 cmdId;
  NSString* groupId;
  UInt32 msgOffset;
  UInt32 msgCount;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupId;
- (BOOL) hasMsgOffset;
- (BOOL) hasMsgCount;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupId;
@property (readonly) UInt32 msgOffset;
@property (readonly) UInt32 msgCount;

+ (C2MGroupHistoryMsgReq*) defaultInstance;
- (C2MGroupHistoryMsgReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupHistoryMsgReqBuilder*) builder;
+ (C2MGroupHistoryMsgReqBuilder*) builder;
+ (C2MGroupHistoryMsgReqBuilder*) builderWithPrototype:(C2MGroupHistoryMsgReq*) prototype;
- (C2MGroupHistoryMsgReqBuilder*) toBuilder;

+ (C2MGroupHistoryMsgReq*) parseFromData:(NSData*) data;
+ (C2MGroupHistoryMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupHistoryMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupHistoryMsgReq* result;
}

- (C2MGroupHistoryMsgReq*) defaultInstance;

- (C2MGroupHistoryMsgReqBuilder*) clear;
- (C2MGroupHistoryMsgReqBuilder*) clone;

- (C2MGroupHistoryMsgReq*) build;
- (C2MGroupHistoryMsgReq*) buildPartial;

- (C2MGroupHistoryMsgReqBuilder*) mergeFrom:(C2MGroupHistoryMsgReq*) other;
- (C2MGroupHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupHistoryMsgReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupHistoryMsgReqBuilder*) clearCmdId;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupHistoryMsgReqBuilder*) setGroupId:(NSString*) value;
- (C2MGroupHistoryMsgReqBuilder*) clearGroupId;

- (BOOL) hasMsgOffset;
- (UInt32) msgOffset;
- (C2MGroupHistoryMsgReqBuilder*) setMsgOffset:(UInt32) value;
- (C2MGroupHistoryMsgReqBuilder*) clearMsgOffset;

- (BOOL) hasMsgCount;
- (UInt32) msgCount;
- (C2MGroupHistoryMsgReqBuilder*) setMsgCount:(UInt32) value;
- (C2MGroupHistoryMsgReqBuilder*) clearMsgCount;
@end

@interface C2MGroupMsgListRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  SInt32 cmdId;
  NSString* groupId;
  NSMutableArray * groupMsgListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSArray * groupMsgList;
- (ClientGroupMsg*)groupMsgListAtIndex:(NSUInteger)index;

+ (C2MGroupMsgListRsp*) defaultInstance;
- (C2MGroupMsgListRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupMsgListRspBuilder*) builder;
+ (C2MGroupMsgListRspBuilder*) builder;
+ (C2MGroupMsgListRspBuilder*) builderWithPrototype:(C2MGroupMsgListRsp*) prototype;
- (C2MGroupMsgListRspBuilder*) toBuilder;

+ (C2MGroupMsgListRsp*) parseFromData:(NSData*) data;
+ (C2MGroupMsgListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupMsgListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupMsgListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupMsgListRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupMsgListRsp* result;
}

- (C2MGroupMsgListRsp*) defaultInstance;

- (C2MGroupMsgListRspBuilder*) clear;
- (C2MGroupMsgListRspBuilder*) clone;

- (C2MGroupMsgListRsp*) build;
- (C2MGroupMsgListRsp*) buildPartial;

- (C2MGroupMsgListRspBuilder*) mergeFrom:(C2MGroupMsgListRsp*) other;
- (C2MGroupMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupMsgListRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupMsgListRspBuilder*) clearCmdId;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupMsgListRspBuilder*) setGroupId:(NSString*) value;
- (C2MGroupMsgListRspBuilder*) clearGroupId;

- (NSMutableArray *)groupMsgList;
- (ClientGroupMsg*)groupMsgListAtIndex:(NSUInteger)index;
- (C2MGroupMsgListRspBuilder *)addGroupMsgList:(ClientGroupMsg*)value;
- (C2MGroupMsgListRspBuilder *)setGroupMsgListArray:(NSArray *)array;
- (C2MGroupMsgListRspBuilder *)clearGroupMsgList;
@end

@interface C2MGroupMsgReadAck : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  SInt32 cmdId;
  NSString* groupId;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupId;

+ (C2MGroupMsgReadAck*) defaultInstance;
- (C2MGroupMsgReadAck*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupMsgReadAckBuilder*) builder;
+ (C2MGroupMsgReadAckBuilder*) builder;
+ (C2MGroupMsgReadAckBuilder*) builderWithPrototype:(C2MGroupMsgReadAck*) prototype;
- (C2MGroupMsgReadAckBuilder*) toBuilder;

+ (C2MGroupMsgReadAck*) parseFromData:(NSData*) data;
+ (C2MGroupMsgReadAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupMsgReadAck*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupMsgReadAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupMsgReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupMsgReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupMsgReadAckBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupMsgReadAck* result;
}

- (C2MGroupMsgReadAck*) defaultInstance;

- (C2MGroupMsgReadAckBuilder*) clear;
- (C2MGroupMsgReadAckBuilder*) clone;

- (C2MGroupMsgReadAck*) build;
- (C2MGroupMsgReadAck*) buildPartial;

- (C2MGroupMsgReadAckBuilder*) mergeFrom:(C2MGroupMsgReadAck*) other;
- (C2MGroupMsgReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupMsgReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupMsgReadAckBuilder*) setCmdId:(SInt32) value;
- (C2MGroupMsgReadAckBuilder*) clearCmdId;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupMsgReadAckBuilder*) setGroupId:(NSString*) value;
- (C2MGroupMsgReadAckBuilder*) clearGroupId;
@end

@interface C2MGroupCreateTmpGroupReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  SInt32 cmdId;
  NSString* groupName;
  NSString* groupAvatar;
  NSMutableArray * userIdListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly, strong) PBArray * userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;

+ (C2MGroupCreateTmpGroupReq*) defaultInstance;
- (C2MGroupCreateTmpGroupReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupCreateTmpGroupReqBuilder*) builder;
+ (C2MGroupCreateTmpGroupReqBuilder*) builder;
+ (C2MGroupCreateTmpGroupReqBuilder*) builderWithPrototype:(C2MGroupCreateTmpGroupReq*) prototype;
- (C2MGroupCreateTmpGroupReqBuilder*) toBuilder;

+ (C2MGroupCreateTmpGroupReq*) parseFromData:(NSData*) data;
+ (C2MGroupCreateTmpGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupCreateTmpGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupCreateTmpGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupCreateTmpGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupCreateTmpGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupCreateTmpGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupCreateTmpGroupReq* result;
}

- (C2MGroupCreateTmpGroupReq*) defaultInstance;

- (C2MGroupCreateTmpGroupReqBuilder*) clear;
- (C2MGroupCreateTmpGroupReqBuilder*) clone;

- (C2MGroupCreateTmpGroupReq*) build;
- (C2MGroupCreateTmpGroupReq*) buildPartial;

- (C2MGroupCreateTmpGroupReqBuilder*) mergeFrom:(C2MGroupCreateTmpGroupReq*) other;
- (C2MGroupCreateTmpGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupCreateTmpGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupCreateTmpGroupReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupCreateTmpGroupReqBuilder*) clearCmdId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (C2MGroupCreateTmpGroupReqBuilder*) setGroupName:(NSString*) value;
- (C2MGroupCreateTmpGroupReqBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (C2MGroupCreateTmpGroupReqBuilder*) setGroupAvatar:(NSString*) value;
- (C2MGroupCreateTmpGroupReqBuilder*) clearGroupAvatar;

- (NSMutableArray *)userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;
- (C2MGroupCreateTmpGroupReqBuilder *)addUserIdList:(NSString*)value;
- (C2MGroupCreateTmpGroupReqBuilder *)setUserIdListArray:(NSArray *)array;
- (C2MGroupCreateTmpGroupReqBuilder *)clearUserIdList;
@end

@interface C2MGroupCreateTmpGroupRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasResults_:1;
  SInt32 cmdId;
  NSString* groupId;
  NSString* groupName;
  UInt32 results;
  NSMutableArray * userIdListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 results;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) PBArray * userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;

+ (C2MGroupCreateTmpGroupRsp*) defaultInstance;
- (C2MGroupCreateTmpGroupRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupCreateTmpGroupRspBuilder*) builder;
+ (C2MGroupCreateTmpGroupRspBuilder*) builder;
+ (C2MGroupCreateTmpGroupRspBuilder*) builderWithPrototype:(C2MGroupCreateTmpGroupRsp*) prototype;
- (C2MGroupCreateTmpGroupRspBuilder*) toBuilder;

+ (C2MGroupCreateTmpGroupRsp*) parseFromData:(NSData*) data;
+ (C2MGroupCreateTmpGroupRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupCreateTmpGroupRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupCreateTmpGroupRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupCreateTmpGroupRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupCreateTmpGroupRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupCreateTmpGroupRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupCreateTmpGroupRsp* result;
}

- (C2MGroupCreateTmpGroupRsp*) defaultInstance;

- (C2MGroupCreateTmpGroupRspBuilder*) clear;
- (C2MGroupCreateTmpGroupRspBuilder*) clone;

- (C2MGroupCreateTmpGroupRsp*) build;
- (C2MGroupCreateTmpGroupRsp*) buildPartial;

- (C2MGroupCreateTmpGroupRspBuilder*) mergeFrom:(C2MGroupCreateTmpGroupRsp*) other;
- (C2MGroupCreateTmpGroupRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupCreateTmpGroupRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupCreateTmpGroupRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupCreateTmpGroupRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (UInt32) results;
- (C2MGroupCreateTmpGroupRspBuilder*) setResults:(UInt32) value;
- (C2MGroupCreateTmpGroupRspBuilder*) clearResults;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupCreateTmpGroupRspBuilder*) setGroupId:(NSString*) value;
- (C2MGroupCreateTmpGroupRspBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (C2MGroupCreateTmpGroupRspBuilder*) setGroupName:(NSString*) value;
- (C2MGroupCreateTmpGroupRspBuilder*) clearGroupName;

- (NSMutableArray *)userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;
- (C2MGroupCreateTmpGroupRspBuilder *)addUserIdList:(NSString*)value;
- (C2MGroupCreateTmpGroupRspBuilder *)setUserIdListArray:(NSArray *)array;
- (C2MGroupCreateTmpGroupRspBuilder *)clearUserIdList;
@end

@interface C2MGroupChangeMemberReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  BOOL hasChangeType_:1;
  SInt32 cmdId;
  NSString* groupId;
  UInt32 changeType;
  NSMutableArray * userIdListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasChangeType;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 changeType;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) PBArray * userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;

+ (C2MGroupChangeMemberReq*) defaultInstance;
- (C2MGroupChangeMemberReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupChangeMemberReqBuilder*) builder;
+ (C2MGroupChangeMemberReqBuilder*) builder;
+ (C2MGroupChangeMemberReqBuilder*) builderWithPrototype:(C2MGroupChangeMemberReq*) prototype;
- (C2MGroupChangeMemberReqBuilder*) toBuilder;

+ (C2MGroupChangeMemberReq*) parseFromData:(NSData*) data;
+ (C2MGroupChangeMemberReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupChangeMemberReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupChangeMemberReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupChangeMemberReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupChangeMemberReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupChangeMemberReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupChangeMemberReq* result;
}

- (C2MGroupChangeMemberReq*) defaultInstance;

- (C2MGroupChangeMemberReqBuilder*) clear;
- (C2MGroupChangeMemberReqBuilder*) clone;

- (C2MGroupChangeMemberReq*) build;
- (C2MGroupChangeMemberReq*) buildPartial;

- (C2MGroupChangeMemberReqBuilder*) mergeFrom:(C2MGroupChangeMemberReq*) other;
- (C2MGroupChangeMemberReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupChangeMemberReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupChangeMemberReqBuilder*) setCmdId:(SInt32) value;
- (C2MGroupChangeMemberReqBuilder*) clearCmdId;

- (BOOL) hasChangeType;
- (UInt32) changeType;
- (C2MGroupChangeMemberReqBuilder*) setChangeType:(UInt32) value;
- (C2MGroupChangeMemberReqBuilder*) clearChangeType;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupChangeMemberReqBuilder*) setGroupId:(NSString*) value;
- (C2MGroupChangeMemberReqBuilder*) clearGroupId;

- (NSMutableArray *)userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;
- (C2MGroupChangeMemberReqBuilder *)addUserIdList:(NSString*)value;
- (C2MGroupChangeMemberReqBuilder *)setUserIdListArray:(NSArray *)array;
- (C2MGroupChangeMemberReqBuilder *)clearUserIdList;
@end

@interface C2MGroupChangeMemberRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasGroupId_:1;
  BOOL hasResults_:1;
  BOOL hasChangeType_:1;
  SInt32 cmdId;
  NSString* groupId;
  UInt32 results;
  UInt32 changeType;
  NSMutableArray * userIdListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
- (BOOL) hasChangeType;
- (BOOL) hasGroupId;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 results;
@property (readonly) UInt32 changeType;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) PBArray * userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;

+ (C2MGroupChangeMemberRsp*) defaultInstance;
- (C2MGroupChangeMemberRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MGroupChangeMemberRspBuilder*) builder;
+ (C2MGroupChangeMemberRspBuilder*) builder;
+ (C2MGroupChangeMemberRspBuilder*) builderWithPrototype:(C2MGroupChangeMemberRsp*) prototype;
- (C2MGroupChangeMemberRspBuilder*) toBuilder;

+ (C2MGroupChangeMemberRsp*) parseFromData:(NSData*) data;
+ (C2MGroupChangeMemberRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupChangeMemberRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MGroupChangeMemberRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MGroupChangeMemberRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MGroupChangeMemberRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MGroupChangeMemberRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MGroupChangeMemberRsp* result;
}

- (C2MGroupChangeMemberRsp*) defaultInstance;

- (C2MGroupChangeMemberRspBuilder*) clear;
- (C2MGroupChangeMemberRspBuilder*) clone;

- (C2MGroupChangeMemberRsp*) build;
- (C2MGroupChangeMemberRsp*) buildPartial;

- (C2MGroupChangeMemberRspBuilder*) mergeFrom:(C2MGroupChangeMemberRsp*) other;
- (C2MGroupChangeMemberRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MGroupChangeMemberRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MGroupChangeMemberRspBuilder*) setCmdId:(SInt32) value;
- (C2MGroupChangeMemberRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (UInt32) results;
- (C2MGroupChangeMemberRspBuilder*) setResults:(UInt32) value;
- (C2MGroupChangeMemberRspBuilder*) clearResults;

- (BOOL) hasChangeType;
- (UInt32) changeType;
- (C2MGroupChangeMemberRspBuilder*) setChangeType:(UInt32) value;
- (C2MGroupChangeMemberRspBuilder*) clearChangeType;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (C2MGroupChangeMemberRspBuilder*) setGroupId:(NSString*) value;
- (C2MGroupChangeMemberRspBuilder*) clearGroupId;

- (NSMutableArray *)userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;
- (C2MGroupChangeMemberRspBuilder *)addUserIdList:(NSString*)value;
- (C2MGroupChangeMemberRspBuilder *)setUserIdListArray:(NSArray *)array;
- (C2MGroupChangeMemberRspBuilder *)clearUserIdList;
@end


// @@protoc_insertion_point(global_scope)
