// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class C2FFileData;
@class C2FFileDataBuilder;
@class C2FFileGetOfflineReq;
@class C2FFileGetOfflineReqBuilder;
@class C2FFileLoginReq;
@class C2FFileLoginReqBuilder;
@class C2FFileLoginRsp;
@class C2FFileLoginRspBuilder;
@class C2FFileUploadFinish;
@class C2FFileUploadFinishBuilder;
@class C2FHeartBeatReq;
@class C2FHeartBeatReqBuilder;
@class C2FHeartBeatRsp;
@class C2FHeartBeatRspBuilder;
@class C2MFileAbort;
@class C2MFileAbortBuilder;
@class C2MFileAddOfflineReq;
@class C2MFileAddOfflineReqBuilder;
@class C2MFileDelOfflineReq;
@class C2MFileDelOfflineReqBuilder;
@class C2MFileDownloadOfflineNotify;
@class C2MFileDownloadOfflineNotifyBuilder;
@class C2MFileHasOfflineReq;
@class C2MFileHasOfflineReqBuilder;
@class C2MFileHasOfflineRsp;
@class C2MFileHasOfflineRspBuilder;
@class C2MFileRecvReady;
@class C2MFileRecvReadyBuilder;
@class C2MFileReq;
@class C2MFileReqBuilder;
@class C2MFileRsp;
@class C2MFileRspBuilder;
@class C2MFileUploadOfflineNotify;
@class C2MFileUploadOfflineNotifyBuilder;
@class ClientGroupInfo;
@class ClientGroupInfoBuilder;
@class ClientGroupMsg;
@class ClientGroupMsgBuilder;
@class ClientGroupUnReadCnt;
@class ClientGroupUnReadCntBuilder;
@class ClientMsgInfo;
@class ClientMsgInfoBuilder;
@class ClientOfflineFileInfo;
@class ClientOfflineFileInfoBuilder;
@class ClientUnReadInfo;
@class ClientUnReadInfoBuilder;
@class ClientUserInfo;
@class ClientUserInfoBuilder;
@class ClientUserStat;
@class ClientUserStatBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class ServerGroupInfo;
@class ServerGroupInfoBuilder;
@class ServerGroupMsg;
@class ServerGroupMsgBuilder;
@class ServerGroupUnReadCnt;
@class ServerGroupUnReadCntBuilder;
@class ServerMsgInfo;
@class ServerMsgInfoBuilder;
@class ServerOfflineFileInfo;
@class ServerOfflineFileInfoBuilder;
@class ServerUnReadInfo;
@class ServerUnReadInfoBuilder;
@class ServerUserInfo;
@class ServerUserInfoBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface Imclient2ServFileRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface C2FHeartBeatReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2FHeartBeatReq*) defaultInstance;
- (C2FHeartBeatReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FHeartBeatReqBuilder*) builder;
+ (C2FHeartBeatReqBuilder*) builder;
+ (C2FHeartBeatReqBuilder*) builderWithPrototype:(C2FHeartBeatReq*) prototype;
- (C2FHeartBeatReqBuilder*) toBuilder;

+ (C2FHeartBeatReq*) parseFromData:(NSData*) data;
+ (C2FHeartBeatReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FHeartBeatReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2FHeartBeatReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FHeartBeatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FHeartBeatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FHeartBeatReqBuilder : PBGeneratedMessageBuilder {
@private
  C2FHeartBeatReq* result;
}

- (C2FHeartBeatReq*) defaultInstance;

- (C2FHeartBeatReqBuilder*) clear;
- (C2FHeartBeatReqBuilder*) clone;

- (C2FHeartBeatReq*) build;
- (C2FHeartBeatReq*) buildPartial;

- (C2FHeartBeatReqBuilder*) mergeFrom:(C2FHeartBeatReq*) other;
- (C2FHeartBeatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FHeartBeatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FHeartBeatReqBuilder*) setCmdId:(SInt32) value;
- (C2FHeartBeatReqBuilder*) clearCmdId;
@end

@interface C2FHeartBeatRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2FHeartBeatRsp*) defaultInstance;
- (C2FHeartBeatRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FHeartBeatRspBuilder*) builder;
+ (C2FHeartBeatRspBuilder*) builder;
+ (C2FHeartBeatRspBuilder*) builderWithPrototype:(C2FHeartBeatRsp*) prototype;
- (C2FHeartBeatRspBuilder*) toBuilder;

+ (C2FHeartBeatRsp*) parseFromData:(NSData*) data;
+ (C2FHeartBeatRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FHeartBeatRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2FHeartBeatRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FHeartBeatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FHeartBeatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FHeartBeatRspBuilder : PBGeneratedMessageBuilder {
@private
  C2FHeartBeatRsp* result;
}

- (C2FHeartBeatRsp*) defaultInstance;

- (C2FHeartBeatRspBuilder*) clear;
- (C2FHeartBeatRspBuilder*) clone;

- (C2FHeartBeatRsp*) build;
- (C2FHeartBeatRsp*) buildPartial;

- (C2FHeartBeatRspBuilder*) mergeFrom:(C2FHeartBeatRsp*) other;
- (C2FHeartBeatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FHeartBeatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FHeartBeatRspBuilder*) setCmdId:(SInt32) value;
- (C2FHeartBeatRspBuilder*) clearCmdId;
@end

@interface C2FFileLoginReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  SInt32 cmdId;
  NSString* userId;
  NSString* token;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserId;
- (BOOL) hasToken;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* token;

+ (C2FFileLoginReq*) defaultInstance;
- (C2FFileLoginReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FFileLoginReqBuilder*) builder;
+ (C2FFileLoginReqBuilder*) builder;
+ (C2FFileLoginReqBuilder*) builderWithPrototype:(C2FFileLoginReq*) prototype;
- (C2FFileLoginReqBuilder*) toBuilder;

+ (C2FFileLoginReq*) parseFromData:(NSData*) data;
+ (C2FFileLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileLoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2FFileLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FFileLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FFileLoginReqBuilder : PBGeneratedMessageBuilder {
@private
  C2FFileLoginReq* result;
}

- (C2FFileLoginReq*) defaultInstance;

- (C2FFileLoginReqBuilder*) clear;
- (C2FFileLoginReqBuilder*) clone;

- (C2FFileLoginReq*) build;
- (C2FFileLoginReq*) buildPartial;

- (C2FFileLoginReqBuilder*) mergeFrom:(C2FFileLoginReq*) other;
- (C2FFileLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FFileLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FFileLoginReqBuilder*) setCmdId:(SInt32) value;
- (C2FFileLoginReqBuilder*) clearCmdId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (C2FFileLoginReqBuilder*) setUserId:(NSString*) value;
- (C2FFileLoginReqBuilder*) clearUserId;

- (BOOL) hasToken;
- (NSString*) token;
- (C2FFileLoginReqBuilder*) setToken:(NSString*) value;
- (C2FFileLoginReqBuilder*) clearToken;
@end

@interface C2FFileLoginRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasResults_:1;
  SInt32 cmdId;
  UInt32 results;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 results;

+ (C2FFileLoginRsp*) defaultInstance;
- (C2FFileLoginRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FFileLoginRspBuilder*) builder;
+ (C2FFileLoginRspBuilder*) builder;
+ (C2FFileLoginRspBuilder*) builderWithPrototype:(C2FFileLoginRsp*) prototype;
- (C2FFileLoginRspBuilder*) toBuilder;

+ (C2FFileLoginRsp*) parseFromData:(NSData*) data;
+ (C2FFileLoginRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileLoginRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2FFileLoginRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FFileLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FFileLoginRspBuilder : PBGeneratedMessageBuilder {
@private
  C2FFileLoginRsp* result;
}

- (C2FFileLoginRsp*) defaultInstance;

- (C2FFileLoginRspBuilder*) clear;
- (C2FFileLoginRspBuilder*) clone;

- (C2FFileLoginRsp*) build;
- (C2FFileLoginRsp*) buildPartial;

- (C2FFileLoginRspBuilder*) mergeFrom:(C2FFileLoginRsp*) other;
- (C2FFileLoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FFileLoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FFileLoginRspBuilder*) setCmdId:(SInt32) value;
- (C2FFileLoginRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (UInt32) results;
- (C2FFileLoginRspBuilder*) setResults:(UInt32) value;
- (C2FFileLoginRspBuilder*) clearResults;
@end

@interface C2FFileData : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileName_:1;
  BOOL hasFileData_:1;
  BOOL hasFileSize_:1;
  BOOL hasFileOffset_:1;
  BOOL hasFileType_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* fileName;
  NSData* fileData;
  UInt32 fileSize;
  UInt32 fileOffset;
  UInt32 fileType;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasFileOffset;
- (BOOL) hasFileType;
- (BOOL) hasFileData;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 fileSize;
@property (readonly) UInt32 fileOffset;
@property (readonly) UInt32 fileType;
@property (readonly, strong) NSData* fileData;

+ (C2FFileData*) defaultInstance;
- (C2FFileData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FFileDataBuilder*) builder;
+ (C2FFileDataBuilder*) builder;
+ (C2FFileDataBuilder*) builderWithPrototype:(C2FFileData*) prototype;
- (C2FFileDataBuilder*) toBuilder;

+ (C2FFileData*) parseFromData:(NSData*) data;
+ (C2FFileData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileData*) parseFromInputStream:(NSInputStream*) input;
+ (C2FFileData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FFileData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FFileDataBuilder : PBGeneratedMessageBuilder {
@private
  C2FFileData* result;
}

- (C2FFileData*) defaultInstance;

- (C2FFileDataBuilder*) clear;
- (C2FFileDataBuilder*) clone;

- (C2FFileData*) build;
- (C2FFileData*) buildPartial;

- (C2FFileDataBuilder*) mergeFrom:(C2FFileData*) other;
- (C2FFileDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FFileDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FFileDataBuilder*) setCmdId:(SInt32) value;
- (C2FFileDataBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2FFileDataBuilder*) setFromUserId:(NSString*) value;
- (C2FFileDataBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2FFileDataBuilder*) setToUserId:(NSString*) value;
- (C2FFileDataBuilder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (C2FFileDataBuilder*) setFileName:(NSString*) value;
- (C2FFileDataBuilder*) clearFileName;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (C2FFileDataBuilder*) setFileSize:(UInt32) value;
- (C2FFileDataBuilder*) clearFileSize;

- (BOOL) hasFileOffset;
- (UInt32) fileOffset;
- (C2FFileDataBuilder*) setFileOffset:(UInt32) value;
- (C2FFileDataBuilder*) clearFileOffset;

- (BOOL) hasFileType;
- (UInt32) fileType;
- (C2FFileDataBuilder*) setFileType:(UInt32) value;
- (C2FFileDataBuilder*) clearFileType;

- (BOOL) hasFileData;
- (NSData*) fileData;
- (C2FFileDataBuilder*) setFileData:(NSData*) value;
- (C2FFileDataBuilder*) clearFileData;
@end

@interface C2FFileGetOfflineReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasFilePath_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* filePath;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasFilePath;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* filePath;

+ (C2FFileGetOfflineReq*) defaultInstance;
- (C2FFileGetOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FFileGetOfflineReqBuilder*) builder;
+ (C2FFileGetOfflineReqBuilder*) builder;
+ (C2FFileGetOfflineReqBuilder*) builderWithPrototype:(C2FFileGetOfflineReq*) prototype;
- (C2FFileGetOfflineReqBuilder*) toBuilder;

+ (C2FFileGetOfflineReq*) parseFromData:(NSData*) data;
+ (C2FFileGetOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileGetOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2FFileGetOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileGetOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FFileGetOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FFileGetOfflineReqBuilder : PBGeneratedMessageBuilder {
@private
  C2FFileGetOfflineReq* result;
}

- (C2FFileGetOfflineReq*) defaultInstance;

- (C2FFileGetOfflineReqBuilder*) clear;
- (C2FFileGetOfflineReqBuilder*) clone;

- (C2FFileGetOfflineReq*) build;
- (C2FFileGetOfflineReq*) buildPartial;

- (C2FFileGetOfflineReqBuilder*) mergeFrom:(C2FFileGetOfflineReq*) other;
- (C2FFileGetOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FFileGetOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FFileGetOfflineReqBuilder*) setCmdId:(SInt32) value;
- (C2FFileGetOfflineReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2FFileGetOfflineReqBuilder*) setFromUserId:(NSString*) value;
- (C2FFileGetOfflineReqBuilder*) clearFromUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2FFileGetOfflineReqBuilder*) setFilePath:(NSString*) value;
- (C2FFileGetOfflineReqBuilder*) clearFilePath;
@end

@interface C2FFileUploadFinish : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFilePath_:1;
  BOOL hasSaveFilePath_:1;
  BOOL hasFileSize_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* filePath;
  NSString* saveFilePath;
  UInt32 fileSize;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFilePath;
- (BOOL) hasSaveFilePath;
- (BOOL) hasFileSize;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* filePath;
@property (readonly, strong) NSString* saveFilePath;
@property (readonly) UInt32 fileSize;

+ (C2FFileUploadFinish*) defaultInstance;
- (C2FFileUploadFinish*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2FFileUploadFinishBuilder*) builder;
+ (C2FFileUploadFinishBuilder*) builder;
+ (C2FFileUploadFinishBuilder*) builderWithPrototype:(C2FFileUploadFinish*) prototype;
- (C2FFileUploadFinishBuilder*) toBuilder;

+ (C2FFileUploadFinish*) parseFromData:(NSData*) data;
+ (C2FFileUploadFinish*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileUploadFinish*) parseFromInputStream:(NSInputStream*) input;
+ (C2FFileUploadFinish*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2FFileUploadFinish*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2FFileUploadFinish*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2FFileUploadFinishBuilder : PBGeneratedMessageBuilder {
@private
  C2FFileUploadFinish* result;
}

- (C2FFileUploadFinish*) defaultInstance;

- (C2FFileUploadFinishBuilder*) clear;
- (C2FFileUploadFinishBuilder*) clone;

- (C2FFileUploadFinish*) build;
- (C2FFileUploadFinish*) buildPartial;

- (C2FFileUploadFinishBuilder*) mergeFrom:(C2FFileUploadFinish*) other;
- (C2FFileUploadFinishBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2FFileUploadFinishBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2FFileUploadFinishBuilder*) setCmdId:(SInt32) value;
- (C2FFileUploadFinishBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2FFileUploadFinishBuilder*) setFromUserId:(NSString*) value;
- (C2FFileUploadFinishBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2FFileUploadFinishBuilder*) setToUserId:(NSString*) value;
- (C2FFileUploadFinishBuilder*) clearToUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2FFileUploadFinishBuilder*) setFilePath:(NSString*) value;
- (C2FFileUploadFinishBuilder*) clearFilePath;

- (BOOL) hasSaveFilePath;
- (NSString*) saveFilePath;
- (C2FFileUploadFinishBuilder*) setSaveFilePath:(NSString*) value;
- (C2FFileUploadFinishBuilder*) clearSaveFilePath;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (C2FFileUploadFinishBuilder*) setFileSize:(UInt32) value;
- (C2FFileUploadFinishBuilder*) clearFileSize;
@end

@interface C2MFileReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileName_:1;
  BOOL hasFileSize_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* fileName;
  UInt32 fileSize;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 fileSize;

+ (C2MFileReq*) defaultInstance;
- (C2MFileReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileReqBuilder*) builder;
+ (C2MFileReqBuilder*) builder;
+ (C2MFileReqBuilder*) builderWithPrototype:(C2MFileReq*) prototype;
- (C2MFileReqBuilder*) toBuilder;

+ (C2MFileReq*) parseFromData:(NSData*) data;
+ (C2MFileReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileReq* result;
}

- (C2MFileReq*) defaultInstance;

- (C2MFileReqBuilder*) clear;
- (C2MFileReqBuilder*) clone;

- (C2MFileReq*) build;
- (C2MFileReq*) buildPartial;

- (C2MFileReqBuilder*) mergeFrom:(C2MFileReq*) other;
- (C2MFileReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileReqBuilder*) setCmdId:(SInt32) value;
- (C2MFileReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileReqBuilder*) setFromUserId:(NSString*) value;
- (C2MFileReqBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileReqBuilder*) setToUserId:(NSString*) value;
- (C2MFileReqBuilder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (C2MFileReqBuilder*) setFileName:(NSString*) value;
- (C2MFileReqBuilder*) clearFileName;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (C2MFileReqBuilder*) setFileSize:(UInt32) value;
- (C2MFileReqBuilder*) clearFileSize;
@end

@interface C2MFileRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileName_:1;
  BOOL hasListenIp_:1;
  BOOL hasAcceptFlag_:1;
  BOOL hasListenPort_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* fileName;
  NSString* listenIp;
  UInt32 acceptFlag;
  UInt32 listenPort;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasAcceptFlag;
- (BOOL) hasListenIp;
- (BOOL) hasListenPort;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 acceptFlag;
@property (readonly, strong) NSString* listenIp;
@property (readonly) UInt32 listenPort;

+ (C2MFileRsp*) defaultInstance;
- (C2MFileRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileRspBuilder*) builder;
+ (C2MFileRspBuilder*) builder;
+ (C2MFileRspBuilder*) builderWithPrototype:(C2MFileRsp*) prototype;
- (C2MFileRspBuilder*) toBuilder;

+ (C2MFileRsp*) parseFromData:(NSData*) data;
+ (C2MFileRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileRsp* result;
}

- (C2MFileRsp*) defaultInstance;

- (C2MFileRspBuilder*) clear;
- (C2MFileRspBuilder*) clone;

- (C2MFileRsp*) build;
- (C2MFileRsp*) buildPartial;

- (C2MFileRspBuilder*) mergeFrom:(C2MFileRsp*) other;
- (C2MFileRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileRspBuilder*) setCmdId:(SInt32) value;
- (C2MFileRspBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileRspBuilder*) setFromUserId:(NSString*) value;
- (C2MFileRspBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileRspBuilder*) setToUserId:(NSString*) value;
- (C2MFileRspBuilder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (C2MFileRspBuilder*) setFileName:(NSString*) value;
- (C2MFileRspBuilder*) clearFileName;

- (BOOL) hasAcceptFlag;
- (UInt32) acceptFlag;
- (C2MFileRspBuilder*) setAcceptFlag:(UInt32) value;
- (C2MFileRspBuilder*) clearAcceptFlag;

- (BOOL) hasListenIp;
- (NSString*) listenIp;
- (C2MFileRspBuilder*) setListenIp:(NSString*) value;
- (C2MFileRspBuilder*) clearListenIp;

- (BOOL) hasListenPort;
- (UInt32) listenPort;
- (C2MFileRspBuilder*) setListenPort:(UInt32) value;
- (C2MFileRspBuilder*) clearListenPort;
@end

@interface C2MFileRecvReady : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;

+ (C2MFileRecvReady*) defaultInstance;
- (C2MFileRecvReady*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileRecvReadyBuilder*) builder;
+ (C2MFileRecvReadyBuilder*) builder;
+ (C2MFileRecvReadyBuilder*) builderWithPrototype:(C2MFileRecvReady*) prototype;
- (C2MFileRecvReadyBuilder*) toBuilder;

+ (C2MFileRecvReady*) parseFromData:(NSData*) data;
+ (C2MFileRecvReady*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileRecvReady*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileRecvReady*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileRecvReady*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileRecvReady*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileRecvReadyBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileRecvReady* result;
}

- (C2MFileRecvReady*) defaultInstance;

- (C2MFileRecvReadyBuilder*) clear;
- (C2MFileRecvReadyBuilder*) clone;

- (C2MFileRecvReady*) build;
- (C2MFileRecvReady*) buildPartial;

- (C2MFileRecvReadyBuilder*) mergeFrom:(C2MFileRecvReady*) other;
- (C2MFileRecvReadyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileRecvReadyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileRecvReadyBuilder*) setCmdId:(SInt32) value;
- (C2MFileRecvReadyBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileRecvReadyBuilder*) setFromUserId:(NSString*) value;
- (C2MFileRecvReadyBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileRecvReadyBuilder*) setToUserId:(NSString*) value;
- (C2MFileRecvReadyBuilder*) clearToUserId;
@end

@interface C2MFileAbort : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFilePath_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* filePath;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFilePath;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* filePath;

+ (C2MFileAbort*) defaultInstance;
- (C2MFileAbort*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileAbortBuilder*) builder;
+ (C2MFileAbortBuilder*) builder;
+ (C2MFileAbortBuilder*) builderWithPrototype:(C2MFileAbort*) prototype;
- (C2MFileAbortBuilder*) toBuilder;

+ (C2MFileAbort*) parseFromData:(NSData*) data;
+ (C2MFileAbort*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileAbort*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileAbort*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileAbort*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileAbort*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileAbortBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileAbort* result;
}

- (C2MFileAbort*) defaultInstance;

- (C2MFileAbortBuilder*) clear;
- (C2MFileAbortBuilder*) clone;

- (C2MFileAbort*) build;
- (C2MFileAbort*) buildPartial;

- (C2MFileAbortBuilder*) mergeFrom:(C2MFileAbort*) other;
- (C2MFileAbortBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileAbortBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileAbortBuilder*) setCmdId:(SInt32) value;
- (C2MFileAbortBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileAbortBuilder*) setFromUserId:(NSString*) value;
- (C2MFileAbortBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileAbortBuilder*) setToUserId:(NSString*) value;
- (C2MFileAbortBuilder*) clearToUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2MFileAbortBuilder*) setFilePath:(NSString*) value;
- (C2MFileAbortBuilder*) clearFilePath;
@end

@interface C2MFileDownloadOfflineNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFilePath_:1;
  BOOL hasSavePath_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* filePath;
  NSString* savePath;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFilePath;
- (BOOL) hasSavePath;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* filePath;
@property (readonly, strong) NSString* savePath;

+ (C2MFileDownloadOfflineNotify*) defaultInstance;
- (C2MFileDownloadOfflineNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileDownloadOfflineNotifyBuilder*) builder;
+ (C2MFileDownloadOfflineNotifyBuilder*) builder;
+ (C2MFileDownloadOfflineNotifyBuilder*) builderWithPrototype:(C2MFileDownloadOfflineNotify*) prototype;
- (C2MFileDownloadOfflineNotifyBuilder*) toBuilder;

+ (C2MFileDownloadOfflineNotify*) parseFromData:(NSData*) data;
+ (C2MFileDownloadOfflineNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileDownloadOfflineNotify*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileDownloadOfflineNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileDownloadOfflineNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileDownloadOfflineNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileDownloadOfflineNotifyBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileDownloadOfflineNotify* result;
}

- (C2MFileDownloadOfflineNotify*) defaultInstance;

- (C2MFileDownloadOfflineNotifyBuilder*) clear;
- (C2MFileDownloadOfflineNotifyBuilder*) clone;

- (C2MFileDownloadOfflineNotify*) build;
- (C2MFileDownloadOfflineNotify*) buildPartial;

- (C2MFileDownloadOfflineNotifyBuilder*) mergeFrom:(C2MFileDownloadOfflineNotify*) other;
- (C2MFileDownloadOfflineNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileDownloadOfflineNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileDownloadOfflineNotifyBuilder*) setCmdId:(SInt32) value;
- (C2MFileDownloadOfflineNotifyBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileDownloadOfflineNotifyBuilder*) setFromUserId:(NSString*) value;
- (C2MFileDownloadOfflineNotifyBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileDownloadOfflineNotifyBuilder*) setToUserId:(NSString*) value;
- (C2MFileDownloadOfflineNotifyBuilder*) clearToUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2MFileDownloadOfflineNotifyBuilder*) setFilePath:(NSString*) value;
- (C2MFileDownloadOfflineNotifyBuilder*) clearFilePath;

- (BOOL) hasSavePath;
- (NSString*) savePath;
- (C2MFileDownloadOfflineNotifyBuilder*) setSavePath:(NSString*) value;
- (C2MFileDownloadOfflineNotifyBuilder*) clearSavePath;
@end

@interface C2MFileUploadOfflineNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFilePath_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* filePath;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFilePath;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* filePath;

+ (C2MFileUploadOfflineNotify*) defaultInstance;
- (C2MFileUploadOfflineNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileUploadOfflineNotifyBuilder*) builder;
+ (C2MFileUploadOfflineNotifyBuilder*) builder;
+ (C2MFileUploadOfflineNotifyBuilder*) builderWithPrototype:(C2MFileUploadOfflineNotify*) prototype;
- (C2MFileUploadOfflineNotifyBuilder*) toBuilder;

+ (C2MFileUploadOfflineNotify*) parseFromData:(NSData*) data;
+ (C2MFileUploadOfflineNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileUploadOfflineNotify*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileUploadOfflineNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileUploadOfflineNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileUploadOfflineNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileUploadOfflineNotifyBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileUploadOfflineNotify* result;
}

- (C2MFileUploadOfflineNotify*) defaultInstance;

- (C2MFileUploadOfflineNotifyBuilder*) clear;
- (C2MFileUploadOfflineNotifyBuilder*) clone;

- (C2MFileUploadOfflineNotify*) build;
- (C2MFileUploadOfflineNotify*) buildPartial;

- (C2MFileUploadOfflineNotifyBuilder*) mergeFrom:(C2MFileUploadOfflineNotify*) other;
- (C2MFileUploadOfflineNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileUploadOfflineNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileUploadOfflineNotifyBuilder*) setCmdId:(SInt32) value;
- (C2MFileUploadOfflineNotifyBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileUploadOfflineNotifyBuilder*) setFromUserId:(NSString*) value;
- (C2MFileUploadOfflineNotifyBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileUploadOfflineNotifyBuilder*) setToUserId:(NSString*) value;
- (C2MFileUploadOfflineNotifyBuilder*) clearToUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2MFileUploadOfflineNotifyBuilder*) setFilePath:(NSString*) value;
- (C2MFileUploadOfflineNotifyBuilder*) clearFilePath;
@end

@interface C2MFileHasOfflineReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MFileHasOfflineReq*) defaultInstance;
- (C2MFileHasOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileHasOfflineReqBuilder*) builder;
+ (C2MFileHasOfflineReqBuilder*) builder;
+ (C2MFileHasOfflineReqBuilder*) builderWithPrototype:(C2MFileHasOfflineReq*) prototype;
- (C2MFileHasOfflineReqBuilder*) toBuilder;

+ (C2MFileHasOfflineReq*) parseFromData:(NSData*) data;
+ (C2MFileHasOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileHasOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileHasOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileHasOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileHasOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileHasOfflineReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileHasOfflineReq* result;
}

- (C2MFileHasOfflineReq*) defaultInstance;

- (C2MFileHasOfflineReqBuilder*) clear;
- (C2MFileHasOfflineReqBuilder*) clone;

- (C2MFileHasOfflineReq*) build;
- (C2MFileHasOfflineReq*) buildPartial;

- (C2MFileHasOfflineReqBuilder*) mergeFrom:(C2MFileHasOfflineReq*) other;
- (C2MFileHasOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileHasOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileHasOfflineReqBuilder*) setCmdId:(SInt32) value;
- (C2MFileHasOfflineReqBuilder*) clearCmdId;
@end

@interface C2MFileHasOfflineRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * offlineFileInfoListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * offlineFileInfoList;
- (ClientOfflineFileInfo*)offlineFileInfoListAtIndex:(NSUInteger)index;

+ (C2MFileHasOfflineRsp*) defaultInstance;
- (C2MFileHasOfflineRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileHasOfflineRspBuilder*) builder;
+ (C2MFileHasOfflineRspBuilder*) builder;
+ (C2MFileHasOfflineRspBuilder*) builderWithPrototype:(C2MFileHasOfflineRsp*) prototype;
- (C2MFileHasOfflineRspBuilder*) toBuilder;

+ (C2MFileHasOfflineRsp*) parseFromData:(NSData*) data;
+ (C2MFileHasOfflineRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileHasOfflineRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileHasOfflineRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileHasOfflineRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileHasOfflineRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileHasOfflineRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileHasOfflineRsp* result;
}

- (C2MFileHasOfflineRsp*) defaultInstance;

- (C2MFileHasOfflineRspBuilder*) clear;
- (C2MFileHasOfflineRspBuilder*) clone;

- (C2MFileHasOfflineRsp*) build;
- (C2MFileHasOfflineRsp*) buildPartial;

- (C2MFileHasOfflineRspBuilder*) mergeFrom:(C2MFileHasOfflineRsp*) other;
- (C2MFileHasOfflineRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileHasOfflineRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileHasOfflineRspBuilder*) setCmdId:(SInt32) value;
- (C2MFileHasOfflineRspBuilder*) clearCmdId;

- (NSMutableArray *)offlineFileInfoList;
- (ClientOfflineFileInfo*)offlineFileInfoListAtIndex:(NSUInteger)index;
- (C2MFileHasOfflineRspBuilder *)addOfflineFileInfoList:(ClientOfflineFileInfo*)value;
- (C2MFileHasOfflineRspBuilder *)setOfflineFileInfoListArray:(NSArray *)array;
- (C2MFileHasOfflineRspBuilder *)clearOfflineFileInfoList;
@end

@interface C2MFileAddOfflineReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFilePath_:1;
  BOOL hasFileSize_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* filePath;
  UInt32 fileSize;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFilePath;
- (BOOL) hasFileSize;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSString* filePath;
@property (readonly) UInt32 fileSize;

+ (C2MFileAddOfflineReq*) defaultInstance;
- (C2MFileAddOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileAddOfflineReqBuilder*) builder;
+ (C2MFileAddOfflineReqBuilder*) builder;
+ (C2MFileAddOfflineReqBuilder*) builderWithPrototype:(C2MFileAddOfflineReq*) prototype;
- (C2MFileAddOfflineReqBuilder*) toBuilder;

+ (C2MFileAddOfflineReq*) parseFromData:(NSData*) data;
+ (C2MFileAddOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileAddOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileAddOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileAddOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileAddOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileAddOfflineReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileAddOfflineReq* result;
}

- (C2MFileAddOfflineReq*) defaultInstance;

- (C2MFileAddOfflineReqBuilder*) clear;
- (C2MFileAddOfflineReqBuilder*) clone;

- (C2MFileAddOfflineReq*) build;
- (C2MFileAddOfflineReq*) buildPartial;

- (C2MFileAddOfflineReqBuilder*) mergeFrom:(C2MFileAddOfflineReq*) other;
- (C2MFileAddOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileAddOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileAddOfflineReqBuilder*) setCmdId:(SInt32) value;
- (C2MFileAddOfflineReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileAddOfflineReqBuilder*) setFromUserId:(NSString*) value;
- (C2MFileAddOfflineReqBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileAddOfflineReqBuilder*) setToUserId:(NSString*) value;
- (C2MFileAddOfflineReqBuilder*) clearToUserId;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (C2MFileAddOfflineReqBuilder*) setFilePath:(NSString*) value;
- (C2MFileAddOfflineReqBuilder*) clearFilePath;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (C2MFileAddOfflineReqBuilder*) setFileSize:(UInt32) value;
- (C2MFileAddOfflineReqBuilder*) clearFileSize;
@end

@interface C2MFileDelOfflineReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileId_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  UInt32 fileId;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly) UInt32 fileId;

+ (C2MFileDelOfflineReq*) defaultInstance;
- (C2MFileDelOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MFileDelOfflineReqBuilder*) builder;
+ (C2MFileDelOfflineReqBuilder*) builder;
+ (C2MFileDelOfflineReqBuilder*) builderWithPrototype:(C2MFileDelOfflineReq*) prototype;
- (C2MFileDelOfflineReqBuilder*) toBuilder;

+ (C2MFileDelOfflineReq*) parseFromData:(NSData*) data;
+ (C2MFileDelOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileDelOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MFileDelOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MFileDelOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MFileDelOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MFileDelOfflineReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MFileDelOfflineReq* result;
}

- (C2MFileDelOfflineReq*) defaultInstance;

- (C2MFileDelOfflineReqBuilder*) clear;
- (C2MFileDelOfflineReqBuilder*) clone;

- (C2MFileDelOfflineReq*) build;
- (C2MFileDelOfflineReq*) buildPartial;

- (C2MFileDelOfflineReqBuilder*) mergeFrom:(C2MFileDelOfflineReq*) other;
- (C2MFileDelOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MFileDelOfflineReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MFileDelOfflineReqBuilder*) setCmdId:(SInt32) value;
- (C2MFileDelOfflineReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MFileDelOfflineReqBuilder*) setFromUserId:(NSString*) value;
- (C2MFileDelOfflineReqBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (C2MFileDelOfflineReqBuilder*) setToUserId:(NSString*) value;
- (C2MFileDelOfflineReqBuilder*) clearToUserId;

- (BOOL) hasFileId;
- (UInt32) fileId;
- (C2MFileDelOfflineReqBuilder*) setFileId:(UInt32) value;
- (C2MFileDelOfflineReqBuilder*) clearFileId;
@end


// @@protoc_insertion_point(global_scope)
