// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class C2LMsgServReq;
@class C2LMsgServReqBuilder;
@class C2LMsgServRsp;
@class C2LMsgServRspBuilder;
@class C2MAllUserReq;
@class C2MAllUserReqBuilder;
@class C2MBuddyListReq;
@class C2MBuddyListReqBuilder;
@class C2MDBQueryReq;
@class C2MDBQueryReqBuilder;
@class C2MDBQueryRsp;
@class C2MDBQueryRspBuilder;
@class C2MHeartBeatReq;
@class C2MHeartBeatReqBuilder;
@class C2MHeartBeatRsp;
@class C2MHeartBeatRspBuilder;
@class C2MHistoryMsgReq;
@class C2MHistoryMsgReqBuilder;
@class C2MLoginReq;
@class C2MLoginReqBuilder;
@class C2MLoginRsp;
@class C2MLoginRspBuilder;
@class C2MMsgListRsp;
@class C2MMsgListRspBuilder;
@class C2MRemoveSessionReq;
@class C2MRemoveSessionReqBuilder;
@class C2MRemoveSessionRsp;
@class C2MRemoveSessionRspBuilder;
@class C2MServiceSetting;
@class C2MServiceSettingBuilder;
@class C2MTimeReq;
@class C2MTimeReqBuilder;
@class C2MTimeRsp;
@class C2MTimeRspBuilder;
@class C2MUnReadMsgCntReq;
@class C2MUnReadMsgCntReqBuilder;
@class C2MUnReadMsgCntRsp;
@class C2MUnReadMsgCntRspBuilder;
@class C2MUnReadMsgReq;
@class C2MUnReadMsgReqBuilder;
@class C2MUserInfoReq;
@class C2MUserInfoReqBuilder;
@class C2MUserInfoRsp;
@class C2MUserInfoRspBuilder;
@class C2MUserListStatReq;
@class C2MUserListStatReqBuilder;
@class C2MUserListStatRsp;
@class C2MUserListStatRspBuilder;
@class C2MUserStatusReq;
@class C2MUserStatusReqBuilder;
@class C2MUserStatusRsp;
@class C2MUserStatusRspBuilder;
@class ClientGroupInfo;
@class ClientGroupInfoBuilder;
@class ClientGroupMsg;
@class ClientGroupMsgBuilder;
@class ClientGroupUnReadCnt;
@class ClientGroupUnReadCntBuilder;
@class ClientMsgData;
@class ClientMsgDataAck;
@class ClientMsgDataAckBuilder;
@class ClientMsgDataBuilder;
@class ClientMsgInfo;
@class ClientMsgInfoBuilder;
@class ClientMsgReadAck;
@class ClientMsgReadAckBuilder;
@class ClientOfflineFileInfo;
@class ClientOfflineFileInfoBuilder;
@class ClientP2PCmdMsg;
@class ClientP2PCmdMsgBuilder;
@class ClientUnReadInfo;
@class ClientUnReadInfoBuilder;
@class ClientUserInfo;
@class ClientUserInfoBuilder;
@class ClientUserStat;
@class ClientUserStatBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class M2CFriendListNotify;
@class M2CFriendListNotifyBuilder;
@class M2CFriendStatNotify;
@class M2CFriendStatNotifyBuilder;
@class M2CKickUserNotify;
@class M2CKickUserNotifyBuilder;
@class M2COnlineFriendListNotify;
@class M2COnlineFriendListNotifyBuilder;
@class ServerGroupInfo;
@class ServerGroupInfoBuilder;
@class ServerGroupMsg;
@class ServerGroupMsgBuilder;
@class ServerGroupUnReadCnt;
@class ServerGroupUnReadCntBuilder;
@class ServerMsgInfo;
@class ServerMsgInfoBuilder;
@class ServerOfflineFileInfo;
@class ServerOfflineFileInfoBuilder;
@class ServerUnReadInfo;
@class ServerUnReadInfoBuilder;
@class ServerUserInfo;
@class ServerUserInfoBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface Imclient2ServBaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface C2LMsgServReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserType_:1;
  SInt32 cmdId;
  UInt32 userType;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserType;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 userType;

+ (C2LMsgServReq*) defaultInstance;
- (C2LMsgServReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2LMsgServReqBuilder*) builder;
+ (C2LMsgServReqBuilder*) builder;
+ (C2LMsgServReqBuilder*) builderWithPrototype:(C2LMsgServReq*) prototype;
- (C2LMsgServReqBuilder*) toBuilder;

+ (C2LMsgServReq*) parseFromData:(NSData*) data;
+ (C2LMsgServReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2LMsgServReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2LMsgServReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2LMsgServReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2LMsgServReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2LMsgServReqBuilder : PBGeneratedMessageBuilder {
@private
  C2LMsgServReq* result;
}

- (C2LMsgServReq*) defaultInstance;

- (C2LMsgServReqBuilder*) clear;
- (C2LMsgServReqBuilder*) clone;

- (C2LMsgServReq*) build;
- (C2LMsgServReq*) buildPartial;

- (C2LMsgServReqBuilder*) mergeFrom:(C2LMsgServReq*) other;
- (C2LMsgServReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2LMsgServReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2LMsgServReqBuilder*) setCmdId:(SInt32) value;
- (C2LMsgServReqBuilder*) clearCmdId;

- (BOOL) hasUserType;
- (UInt32) userType;
- (C2LMsgServReqBuilder*) setUserType:(UInt32) value;
- (C2LMsgServReqBuilder*) clearUserType;
@end

@interface C2LMsgServRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasResults_:1;
  SInt32 cmdId;
  ResultType results;
  NSMutableArray * ipAddrListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
@property (readonly) SInt32 cmdId;
@property (readonly) ResultType results;
@property (readonly, strong) NSArray * ipAddrList;
- (IpAddr*)ipAddrListAtIndex:(NSUInteger)index;

+ (C2LMsgServRsp*) defaultInstance;
- (C2LMsgServRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2LMsgServRspBuilder*) builder;
+ (C2LMsgServRspBuilder*) builder;
+ (C2LMsgServRspBuilder*) builderWithPrototype:(C2LMsgServRsp*) prototype;
- (C2LMsgServRspBuilder*) toBuilder;

+ (C2LMsgServRsp*) parseFromData:(NSData*) data;
+ (C2LMsgServRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2LMsgServRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2LMsgServRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2LMsgServRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2LMsgServRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2LMsgServRspBuilder : PBGeneratedMessageBuilder {
@private
  C2LMsgServRsp* result;
}

- (C2LMsgServRsp*) defaultInstance;

- (C2LMsgServRspBuilder*) clear;
- (C2LMsgServRspBuilder*) clone;

- (C2LMsgServRsp*) build;
- (C2LMsgServRsp*) buildPartial;

- (C2LMsgServRspBuilder*) mergeFrom:(C2LMsgServRsp*) other;
- (C2LMsgServRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2LMsgServRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2LMsgServRspBuilder*) setCmdId:(SInt32) value;
- (C2LMsgServRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (ResultType) results;
- (C2LMsgServRspBuilder*) setResults:(ResultType) value;
- (C2LMsgServRspBuilder*) clearResults;

- (NSMutableArray *)ipAddrList;
- (IpAddr*)ipAddrListAtIndex:(NSUInteger)index;
- (C2LMsgServRspBuilder *)addIpAddrList:(IpAddr*)value;
- (C2LMsgServRspBuilder *)setIpAddrListArray:(NSArray *)array;
- (C2LMsgServRspBuilder *)clearIpAddrList;
@end

@interface C2MHeartBeatReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MHeartBeatReq*) defaultInstance;
- (C2MHeartBeatReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MHeartBeatReqBuilder*) builder;
+ (C2MHeartBeatReqBuilder*) builder;
+ (C2MHeartBeatReqBuilder*) builderWithPrototype:(C2MHeartBeatReq*) prototype;
- (C2MHeartBeatReqBuilder*) toBuilder;

+ (C2MHeartBeatReq*) parseFromData:(NSData*) data;
+ (C2MHeartBeatReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHeartBeatReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MHeartBeatReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHeartBeatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MHeartBeatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MHeartBeatReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MHeartBeatReq* result;
}

- (C2MHeartBeatReq*) defaultInstance;

- (C2MHeartBeatReqBuilder*) clear;
- (C2MHeartBeatReqBuilder*) clone;

- (C2MHeartBeatReq*) build;
- (C2MHeartBeatReq*) buildPartial;

- (C2MHeartBeatReqBuilder*) mergeFrom:(C2MHeartBeatReq*) other;
- (C2MHeartBeatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MHeartBeatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MHeartBeatReqBuilder*) setCmdId:(SInt32) value;
- (C2MHeartBeatReqBuilder*) clearCmdId;
@end

@interface C2MHeartBeatRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MHeartBeatRsp*) defaultInstance;
- (C2MHeartBeatRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MHeartBeatRspBuilder*) builder;
+ (C2MHeartBeatRspBuilder*) builder;
+ (C2MHeartBeatRspBuilder*) builderWithPrototype:(C2MHeartBeatRsp*) prototype;
- (C2MHeartBeatRspBuilder*) toBuilder;

+ (C2MHeartBeatRsp*) parseFromData:(NSData*) data;
+ (C2MHeartBeatRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHeartBeatRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MHeartBeatRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHeartBeatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MHeartBeatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MHeartBeatRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MHeartBeatRsp* result;
}

- (C2MHeartBeatRsp*) defaultInstance;

- (C2MHeartBeatRspBuilder*) clear;
- (C2MHeartBeatRspBuilder*) clone;

- (C2MHeartBeatRsp*) build;
- (C2MHeartBeatRsp*) buildPartial;

- (C2MHeartBeatRspBuilder*) mergeFrom:(C2MHeartBeatRsp*) other;
- (C2MHeartBeatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MHeartBeatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MHeartBeatRspBuilder*) setCmdId:(SInt32) value;
- (C2MHeartBeatRspBuilder*) clearCmdId;
@end

@interface C2MLoginReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserId_:1;
  BOOL hasUuid_:1;
  BOOL hasClientVersion_:1;
  BOOL hasOnlineStatus_:1;
  SInt32 cmdId;
  NSString* userId;
  NSString* uuid;
  NSString* clientVersion;
  UInt32 onlineStatus;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserId;
- (BOOL) hasUuid;
- (BOOL) hasOnlineStatus;
- (BOOL) hasClientVersion;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* uuid;
@property (readonly) UInt32 onlineStatus;
@property (readonly, strong) NSString* clientVersion;

+ (C2MLoginReq*) defaultInstance;
- (C2MLoginReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MLoginReqBuilder*) builder;
+ (C2MLoginReqBuilder*) builder;
+ (C2MLoginReqBuilder*) builderWithPrototype:(C2MLoginReq*) prototype;
- (C2MLoginReqBuilder*) toBuilder;

+ (C2MLoginReq*) parseFromData:(NSData*) data;
+ (C2MLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MLoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MLoginReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MLoginReq* result;
}

- (C2MLoginReq*) defaultInstance;

- (C2MLoginReqBuilder*) clear;
- (C2MLoginReqBuilder*) clone;

- (C2MLoginReq*) build;
- (C2MLoginReq*) buildPartial;

- (C2MLoginReqBuilder*) mergeFrom:(C2MLoginReq*) other;
- (C2MLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MLoginReqBuilder*) setCmdId:(SInt32) value;
- (C2MLoginReqBuilder*) clearCmdId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (C2MLoginReqBuilder*) setUserId:(NSString*) value;
- (C2MLoginReqBuilder*) clearUserId;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (C2MLoginReqBuilder*) setUuid:(NSString*) value;
- (C2MLoginReqBuilder*) clearUuid;

- (BOOL) hasOnlineStatus;
- (UInt32) onlineStatus;
- (C2MLoginReqBuilder*) setOnlineStatus:(UInt32) value;
- (C2MLoginReqBuilder*) clearOnlineStatus;

- (BOOL) hasClientVersion;
- (NSString*) clientVersion;
- (C2MLoginReqBuilder*) setClientVersion:(NSString*) value;
- (C2MLoginReqBuilder*) clearClientVersion;
@end

@interface C2MLoginRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasName_:1;
  BOOL hasNickName_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasServerTime_:1;
  BOOL hasOnlineStatus_:1;
  BOOL hasResults_:1;
  BOOL hasUserType_:1;
  SInt32 cmdId;
  NSString* name;
  NSString* nickName;
  NSString* avatarUrl;
  UInt32 serverTime;
  UInt32 onlineStatus;
  ResultType results;
  UserType userType;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
- (BOOL) hasServerTime;
- (BOOL) hasOnlineStatus;
- (BOOL) hasName;
- (BOOL) hasNickName;
- (BOOL) hasAvatarUrl;
- (BOOL) hasUserType;
@property (readonly) SInt32 cmdId;
@property (readonly) ResultType results;
@property (readonly) UInt32 serverTime;
@property (readonly) UInt32 onlineStatus;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* avatarUrl;
@property (readonly) UserType userType;

+ (C2MLoginRsp*) defaultInstance;
- (C2MLoginRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MLoginRspBuilder*) builder;
+ (C2MLoginRspBuilder*) builder;
+ (C2MLoginRspBuilder*) builderWithPrototype:(C2MLoginRsp*) prototype;
- (C2MLoginRspBuilder*) toBuilder;

+ (C2MLoginRsp*) parseFromData:(NSData*) data;
+ (C2MLoginRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MLoginRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MLoginRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MLoginRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MLoginRsp* result;
}

- (C2MLoginRsp*) defaultInstance;

- (C2MLoginRspBuilder*) clear;
- (C2MLoginRspBuilder*) clone;

- (C2MLoginRsp*) build;
- (C2MLoginRsp*) buildPartial;

- (C2MLoginRspBuilder*) mergeFrom:(C2MLoginRsp*) other;
- (C2MLoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MLoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MLoginRspBuilder*) setCmdId:(SInt32) value;
- (C2MLoginRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (ResultType) results;
- (C2MLoginRspBuilder*) setResults:(ResultType) value;
- (C2MLoginRspBuilder*) clearResults;

- (BOOL) hasServerTime;
- (UInt32) serverTime;
- (C2MLoginRspBuilder*) setServerTime:(UInt32) value;
- (C2MLoginRspBuilder*) clearServerTime;

- (BOOL) hasOnlineStatus;
- (UInt32) onlineStatus;
- (C2MLoginRspBuilder*) setOnlineStatus:(UInt32) value;
- (C2MLoginRspBuilder*) clearOnlineStatus;

- (BOOL) hasName;
- (NSString*) name;
- (C2MLoginRspBuilder*) setName:(NSString*) value;
- (C2MLoginRspBuilder*) clearName;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (C2MLoginRspBuilder*) setNickName:(NSString*) value;
- (C2MLoginRspBuilder*) clearNickName;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (C2MLoginRspBuilder*) setAvatarUrl:(NSString*) value;
- (C2MLoginRspBuilder*) clearAvatarUrl;

- (BOOL) hasUserType;
- (UserType) userType;
- (C2MLoginRspBuilder*) setUserType:(UserType) value;
- (C2MLoginRspBuilder*) clearUserType;
@end

@interface M2CKickUserNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserId_:1;
  BOOL hasKickReason_:1;
  SInt32 cmdId;
  NSString* userId;
  KickReasonType kickReason;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserId;
- (BOOL) hasKickReason;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* userId;
@property (readonly) KickReasonType kickReason;

+ (M2CKickUserNotify*) defaultInstance;
- (M2CKickUserNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (M2CKickUserNotifyBuilder*) builder;
+ (M2CKickUserNotifyBuilder*) builder;
+ (M2CKickUserNotifyBuilder*) builderWithPrototype:(M2CKickUserNotify*) prototype;
- (M2CKickUserNotifyBuilder*) toBuilder;

+ (M2CKickUserNotify*) parseFromData:(NSData*) data;
+ (M2CKickUserNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CKickUserNotify*) parseFromInputStream:(NSInputStream*) input;
+ (M2CKickUserNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CKickUserNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (M2CKickUserNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface M2CKickUserNotifyBuilder : PBGeneratedMessageBuilder {
@private
  M2CKickUserNotify* result;
}

- (M2CKickUserNotify*) defaultInstance;

- (M2CKickUserNotifyBuilder*) clear;
- (M2CKickUserNotifyBuilder*) clone;

- (M2CKickUserNotify*) build;
- (M2CKickUserNotify*) buildPartial;

- (M2CKickUserNotifyBuilder*) mergeFrom:(M2CKickUserNotify*) other;
- (M2CKickUserNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (M2CKickUserNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (M2CKickUserNotifyBuilder*) setCmdId:(SInt32) value;
- (M2CKickUserNotifyBuilder*) clearCmdId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (M2CKickUserNotifyBuilder*) setUserId:(NSString*) value;
- (M2CKickUserNotifyBuilder*) clearUserId;

- (BOOL) hasKickReason;
- (KickReasonType) kickReason;
- (M2CKickUserNotifyBuilder*) setKickReason:(KickReasonType) value;
- (M2CKickUserNotifyBuilder*) clearKickReason;
@end

@interface C2MBuddyListReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasReqType_:1;
  SInt32 cmdId;
  UInt32 reqType;
}
- (BOOL) hasCmdId;
- (BOOL) hasReqType;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 reqType;

+ (C2MBuddyListReq*) defaultInstance;
- (C2MBuddyListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MBuddyListReqBuilder*) builder;
+ (C2MBuddyListReqBuilder*) builder;
+ (C2MBuddyListReqBuilder*) builderWithPrototype:(C2MBuddyListReq*) prototype;
- (C2MBuddyListReqBuilder*) toBuilder;

+ (C2MBuddyListReq*) parseFromData:(NSData*) data;
+ (C2MBuddyListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MBuddyListReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MBuddyListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MBuddyListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MBuddyListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MBuddyListReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MBuddyListReq* result;
}

- (C2MBuddyListReq*) defaultInstance;

- (C2MBuddyListReqBuilder*) clear;
- (C2MBuddyListReqBuilder*) clone;

- (C2MBuddyListReq*) build;
- (C2MBuddyListReq*) buildPartial;

- (C2MBuddyListReqBuilder*) mergeFrom:(C2MBuddyListReq*) other;
- (C2MBuddyListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MBuddyListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MBuddyListReqBuilder*) setCmdId:(SInt32) value;
- (C2MBuddyListReqBuilder*) clearCmdId;

- (BOOL) hasReqType;
- (UInt32) reqType;
- (C2MBuddyListReqBuilder*) setReqType:(UInt32) value;
- (C2MBuddyListReqBuilder*) clearReqType;
@end

@interface M2CFriendListNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * friendListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * friendList;
- (ClientUserInfo*)friendListAtIndex:(NSUInteger)index;

+ (M2CFriendListNotify*) defaultInstance;
- (M2CFriendListNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (M2CFriendListNotifyBuilder*) builder;
+ (M2CFriendListNotifyBuilder*) builder;
+ (M2CFriendListNotifyBuilder*) builderWithPrototype:(M2CFriendListNotify*) prototype;
- (M2CFriendListNotifyBuilder*) toBuilder;

+ (M2CFriendListNotify*) parseFromData:(NSData*) data;
+ (M2CFriendListNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CFriendListNotify*) parseFromInputStream:(NSInputStream*) input;
+ (M2CFriendListNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CFriendListNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (M2CFriendListNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface M2CFriendListNotifyBuilder : PBGeneratedMessageBuilder {
@private
  M2CFriendListNotify* result;
}

- (M2CFriendListNotify*) defaultInstance;

- (M2CFriendListNotifyBuilder*) clear;
- (M2CFriendListNotifyBuilder*) clone;

- (M2CFriendListNotify*) build;
- (M2CFriendListNotify*) buildPartial;

- (M2CFriendListNotifyBuilder*) mergeFrom:(M2CFriendListNotify*) other;
- (M2CFriendListNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (M2CFriendListNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (M2CFriendListNotifyBuilder*) setCmdId:(SInt32) value;
- (M2CFriendListNotifyBuilder*) clearCmdId;

- (NSMutableArray *)friendList;
- (ClientUserInfo*)friendListAtIndex:(NSUInteger)index;
- (M2CFriendListNotifyBuilder *)addFriendList:(ClientUserInfo*)value;
- (M2CFriendListNotifyBuilder *)setFriendListArray:(NSArray *)array;
- (M2CFriendListNotifyBuilder *)clearFriendList;
@end

@interface M2COnlineFriendListNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasListType_:1;
  SInt32 cmdId;
  OnlineListType listType;
  NSMutableArray * friendStatusListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasListType;
@property (readonly) SInt32 cmdId;
@property (readonly) OnlineListType listType;
@property (readonly, strong) NSArray * friendStatusList;
- (ClientUserStat*)friendStatusListAtIndex:(NSUInteger)index;

+ (M2COnlineFriendListNotify*) defaultInstance;
- (M2COnlineFriendListNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (M2COnlineFriendListNotifyBuilder*) builder;
+ (M2COnlineFriendListNotifyBuilder*) builder;
+ (M2COnlineFriendListNotifyBuilder*) builderWithPrototype:(M2COnlineFriendListNotify*) prototype;
- (M2COnlineFriendListNotifyBuilder*) toBuilder;

+ (M2COnlineFriendListNotify*) parseFromData:(NSData*) data;
+ (M2COnlineFriendListNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2COnlineFriendListNotify*) parseFromInputStream:(NSInputStream*) input;
+ (M2COnlineFriendListNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2COnlineFriendListNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (M2COnlineFriendListNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface M2COnlineFriendListNotifyBuilder : PBGeneratedMessageBuilder {
@private
  M2COnlineFriendListNotify* result;
}

- (M2COnlineFriendListNotify*) defaultInstance;

- (M2COnlineFriendListNotifyBuilder*) clear;
- (M2COnlineFriendListNotifyBuilder*) clone;

- (M2COnlineFriendListNotify*) build;
- (M2COnlineFriendListNotify*) buildPartial;

- (M2COnlineFriendListNotifyBuilder*) mergeFrom:(M2COnlineFriendListNotify*) other;
- (M2COnlineFriendListNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (M2COnlineFriendListNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (M2COnlineFriendListNotifyBuilder*) setCmdId:(SInt32) value;
- (M2COnlineFriendListNotifyBuilder*) clearCmdId;

- (BOOL) hasListType;
- (OnlineListType) listType;
- (M2COnlineFriendListNotifyBuilder*) setListType:(OnlineListType) value;
- (M2COnlineFriendListNotifyBuilder*) clearListType;

- (NSMutableArray *)friendStatusList;
- (ClientUserStat*)friendStatusListAtIndex:(NSUInteger)index;
- (M2COnlineFriendListNotifyBuilder *)addFriendStatusList:(ClientUserStat*)value;
- (M2COnlineFriendListNotifyBuilder *)setFriendStatusListArray:(NSArray *)array;
- (M2COnlineFriendListNotifyBuilder *)clearFriendStatusList;
@end

@interface M2CFriendStatNotify : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserStat_:1;
  SInt32 cmdId;
  ClientUserStat* userStat;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserStat;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) ClientUserStat* userStat;

+ (M2CFriendStatNotify*) defaultInstance;
- (M2CFriendStatNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (M2CFriendStatNotifyBuilder*) builder;
+ (M2CFriendStatNotifyBuilder*) builder;
+ (M2CFriendStatNotifyBuilder*) builderWithPrototype:(M2CFriendStatNotify*) prototype;
- (M2CFriendStatNotifyBuilder*) toBuilder;

+ (M2CFriendStatNotify*) parseFromData:(NSData*) data;
+ (M2CFriendStatNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CFriendStatNotify*) parseFromInputStream:(NSInputStream*) input;
+ (M2CFriendStatNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (M2CFriendStatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (M2CFriendStatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface M2CFriendStatNotifyBuilder : PBGeneratedMessageBuilder {
@private
  M2CFriendStatNotify* result;
}

- (M2CFriendStatNotify*) defaultInstance;

- (M2CFriendStatNotifyBuilder*) clear;
- (M2CFriendStatNotifyBuilder*) clone;

- (M2CFriendStatNotify*) build;
- (M2CFriendStatNotify*) buildPartial;

- (M2CFriendStatNotifyBuilder*) mergeFrom:(M2CFriendStatNotify*) other;
- (M2CFriendStatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (M2CFriendStatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (M2CFriendStatNotifyBuilder*) setCmdId:(SInt32) value;
- (M2CFriendStatNotifyBuilder*) clearCmdId;

- (BOOL) hasUserStat;
- (ClientUserStat*) userStat;
- (M2CFriendStatNotifyBuilder*) setUserStat:(ClientUserStat*) value;
- (M2CFriendStatNotifyBuilder*) setUserStatBuilder:(ClientUserStatBuilder*) builderForValue;
- (M2CFriendStatNotifyBuilder*) mergeUserStat:(ClientUserStat*) value;
- (M2CFriendStatNotifyBuilder*) clearUserStat;
@end

@interface C2MUserStatusReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserId_:1;
  SInt32 cmdId;
  NSString* userId;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* userId;

+ (C2MUserStatusReq*) defaultInstance;
- (C2MUserStatusReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserStatusReqBuilder*) builder;
+ (C2MUserStatusReqBuilder*) builder;
+ (C2MUserStatusReqBuilder*) builderWithPrototype:(C2MUserStatusReq*) prototype;
- (C2MUserStatusReqBuilder*) toBuilder;

+ (C2MUserStatusReq*) parseFromData:(NSData*) data;
+ (C2MUserStatusReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserStatusReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserStatusReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserStatusReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserStatusReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserStatusReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserStatusReq* result;
}

- (C2MUserStatusReq*) defaultInstance;

- (C2MUserStatusReqBuilder*) clear;
- (C2MUserStatusReqBuilder*) clone;

- (C2MUserStatusReq*) build;
- (C2MUserStatusReq*) buildPartial;

- (C2MUserStatusReqBuilder*) mergeFrom:(C2MUserStatusReq*) other;
- (C2MUserStatusReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserStatusReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserStatusReqBuilder*) setCmdId:(SInt32) value;
- (C2MUserStatusReqBuilder*) clearCmdId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (C2MUserStatusReqBuilder*) setUserId:(NSString*) value;
- (C2MUserStatusReqBuilder*) clearUserId;
@end

@interface C2MUserStatusRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasUserStat_:1;
  SInt32 cmdId;
  ClientUserStat* userStat;
}
- (BOOL) hasCmdId;
- (BOOL) hasUserStat;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) ClientUserStat* userStat;

+ (C2MUserStatusRsp*) defaultInstance;
- (C2MUserStatusRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserStatusRspBuilder*) builder;
+ (C2MUserStatusRspBuilder*) builder;
+ (C2MUserStatusRspBuilder*) builderWithPrototype:(C2MUserStatusRsp*) prototype;
- (C2MUserStatusRspBuilder*) toBuilder;

+ (C2MUserStatusRsp*) parseFromData:(NSData*) data;
+ (C2MUserStatusRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserStatusRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserStatusRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserStatusRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserStatusRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserStatusRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserStatusRsp* result;
}

- (C2MUserStatusRsp*) defaultInstance;

- (C2MUserStatusRspBuilder*) clear;
- (C2MUserStatusRspBuilder*) clone;

- (C2MUserStatusRsp*) build;
- (C2MUserStatusRsp*) buildPartial;

- (C2MUserStatusRspBuilder*) mergeFrom:(C2MUserStatusRsp*) other;
- (C2MUserStatusRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserStatusRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserStatusRspBuilder*) setCmdId:(SInt32) value;
- (C2MUserStatusRspBuilder*) clearCmdId;

- (BOOL) hasUserStat;
- (ClientUserStat*) userStat;
- (C2MUserStatusRspBuilder*) setUserStat:(ClientUserStat*) value;
- (C2MUserStatusRspBuilder*) setUserStatBuilder:(ClientUserStatBuilder*) builderForValue;
- (C2MUserStatusRspBuilder*) mergeUserStat:(ClientUserStat*) value;
- (C2MUserStatusRspBuilder*) clearUserStat;
@end

@interface C2MUserListStatReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * userListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) PBArray * userList;
- (NSString*)userListAtIndex:(NSUInteger)index;

+ (C2MUserListStatReq*) defaultInstance;
- (C2MUserListStatReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserListStatReqBuilder*) builder;
+ (C2MUserListStatReqBuilder*) builder;
+ (C2MUserListStatReqBuilder*) builderWithPrototype:(C2MUserListStatReq*) prototype;
- (C2MUserListStatReqBuilder*) toBuilder;

+ (C2MUserListStatReq*) parseFromData:(NSData*) data;
+ (C2MUserListStatReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserListStatReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserListStatReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserListStatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserListStatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserListStatReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserListStatReq* result;
}

- (C2MUserListStatReq*) defaultInstance;

- (C2MUserListStatReqBuilder*) clear;
- (C2MUserListStatReqBuilder*) clone;

- (C2MUserListStatReq*) build;
- (C2MUserListStatReq*) buildPartial;

- (C2MUserListStatReqBuilder*) mergeFrom:(C2MUserListStatReq*) other;
- (C2MUserListStatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserListStatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserListStatReqBuilder*) setCmdId:(SInt32) value;
- (C2MUserListStatReqBuilder*) clearCmdId;

- (NSMutableArray *)userList;
- (NSString*)userListAtIndex:(NSUInteger)index;
- (C2MUserListStatReqBuilder *)addUserList:(NSString*)value;
- (C2MUserListStatReqBuilder *)setUserListArray:(NSArray *)array;
- (C2MUserListStatReqBuilder *)clearUserList;
@end

@interface C2MUserListStatRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * userStatListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * userStatList;
- (ClientUserStat*)userStatListAtIndex:(NSUInteger)index;

+ (C2MUserListStatRsp*) defaultInstance;
- (C2MUserListStatRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserListStatRspBuilder*) builder;
+ (C2MUserListStatRspBuilder*) builder;
+ (C2MUserListStatRspBuilder*) builderWithPrototype:(C2MUserListStatRsp*) prototype;
- (C2MUserListStatRspBuilder*) toBuilder;

+ (C2MUserListStatRsp*) parseFromData:(NSData*) data;
+ (C2MUserListStatRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserListStatRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserListStatRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserListStatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserListStatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserListStatRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserListStatRsp* result;
}

- (C2MUserListStatRsp*) defaultInstance;

- (C2MUserListStatRspBuilder*) clear;
- (C2MUserListStatRspBuilder*) clone;

- (C2MUserListStatRsp*) build;
- (C2MUserListStatRsp*) buildPartial;

- (C2MUserListStatRspBuilder*) mergeFrom:(C2MUserListStatRsp*) other;
- (C2MUserListStatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserListStatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserListStatRspBuilder*) setCmdId:(SInt32) value;
- (C2MUserListStatRspBuilder*) clearCmdId;

- (NSMutableArray *)userStatList;
- (ClientUserStat*)userStatListAtIndex:(NSUInteger)index;
- (C2MUserListStatRspBuilder *)addUserStatList:(ClientUserStat*)value;
- (C2MUserListStatRspBuilder *)setUserStatListArray:(NSArray *)array;
- (C2MUserListStatRspBuilder *)clearUserStatList;
@end

@interface ClientMsgData : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasMsgData_:1;
  BOOL hasAttachData_:1;
  BOOL hasSeqNo_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  BOOL hasRenderType_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* msgData;
  NSData* attachData;
  UInt32 seqNo;
  UInt32 createTime;
  UInt32 msgType;
  UInt32 renderType;
}
- (BOOL) hasCmdId;
- (BOOL) hasSeqNo;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasRenderType;
- (BOOL) hasMsgData;
- (BOOL) hasAttachData;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 seqNo;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly) UInt32 createTime;
@property (readonly) UInt32 msgType;
@property (readonly) UInt32 renderType;
@property (readonly, strong) NSString* msgData;
@property (readonly, strong) NSData* attachData;

+ (ClientMsgData*) defaultInstance;
- (ClientMsgData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientMsgDataBuilder*) builder;
+ (ClientMsgDataBuilder*) builder;
+ (ClientMsgDataBuilder*) builderWithPrototype:(ClientMsgData*) prototype;
- (ClientMsgDataBuilder*) toBuilder;

+ (ClientMsgData*) parseFromData:(NSData*) data;
+ (ClientMsgData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgData*) parseFromInputStream:(NSInputStream*) input;
+ (ClientMsgData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientMsgData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientMsgDataBuilder : PBGeneratedMessageBuilder {
@private
  ClientMsgData* result;
}

- (ClientMsgData*) defaultInstance;

- (ClientMsgDataBuilder*) clear;
- (ClientMsgDataBuilder*) clone;

- (ClientMsgData*) build;
- (ClientMsgData*) buildPartial;

- (ClientMsgDataBuilder*) mergeFrom:(ClientMsgData*) other;
- (ClientMsgDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientMsgDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (ClientMsgDataBuilder*) setCmdId:(SInt32) value;
- (ClientMsgDataBuilder*) clearCmdId;

- (BOOL) hasSeqNo;
- (UInt32) seqNo;
- (ClientMsgDataBuilder*) setSeqNo:(UInt32) value;
- (ClientMsgDataBuilder*) clearSeqNo;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientMsgDataBuilder*) setFromUserId:(NSString*) value;
- (ClientMsgDataBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (ClientMsgDataBuilder*) setToUserId:(NSString*) value;
- (ClientMsgDataBuilder*) clearToUserId;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (ClientMsgDataBuilder*) setCreateTime:(UInt32) value;
- (ClientMsgDataBuilder*) clearCreateTime;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (ClientMsgDataBuilder*) setMsgType:(UInt32) value;
- (ClientMsgDataBuilder*) clearMsgType;

- (BOOL) hasRenderType;
- (UInt32) renderType;
- (ClientMsgDataBuilder*) setRenderType:(UInt32) value;
- (ClientMsgDataBuilder*) clearRenderType;

- (BOOL) hasMsgData;
- (NSString*) msgData;
- (ClientMsgDataBuilder*) setMsgData:(NSString*) value;
- (ClientMsgDataBuilder*) clearMsgData;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (ClientMsgDataBuilder*) setAttachData:(NSData*) value;
- (ClientMsgDataBuilder*) clearAttachData;
@end

@interface ClientMsgDataAck : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasSeqNo_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  UInt32 seqNo;
}
- (BOOL) hasCmdId;
- (BOOL) hasSeqNo;
- (BOOL) hasFromUserId;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 seqNo;
@property (readonly, strong) NSString* fromUserId;

+ (ClientMsgDataAck*) defaultInstance;
- (ClientMsgDataAck*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientMsgDataAckBuilder*) builder;
+ (ClientMsgDataAckBuilder*) builder;
+ (ClientMsgDataAckBuilder*) builderWithPrototype:(ClientMsgDataAck*) prototype;
- (ClientMsgDataAckBuilder*) toBuilder;

+ (ClientMsgDataAck*) parseFromData:(NSData*) data;
+ (ClientMsgDataAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgDataAck*) parseFromInputStream:(NSInputStream*) input;
+ (ClientMsgDataAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgDataAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientMsgDataAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientMsgDataAckBuilder : PBGeneratedMessageBuilder {
@private
  ClientMsgDataAck* result;
}

- (ClientMsgDataAck*) defaultInstance;

- (ClientMsgDataAckBuilder*) clear;
- (ClientMsgDataAckBuilder*) clone;

- (ClientMsgDataAck*) build;
- (ClientMsgDataAck*) buildPartial;

- (ClientMsgDataAckBuilder*) mergeFrom:(ClientMsgDataAck*) other;
- (ClientMsgDataAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientMsgDataAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (ClientMsgDataAckBuilder*) setCmdId:(SInt32) value;
- (ClientMsgDataAckBuilder*) clearCmdId;

- (BOOL) hasSeqNo;
- (UInt32) seqNo;
- (ClientMsgDataAckBuilder*) setSeqNo:(UInt32) value;
- (ClientMsgDataAckBuilder*) clearSeqNo;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientMsgDataAckBuilder*) setFromUserId:(NSString*) value;
- (ClientMsgDataAckBuilder*) clearFromUserId;
@end

@interface ClientMsgReadAck : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  SInt32 cmdId;
  NSString* fromUserId;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;

+ (ClientMsgReadAck*) defaultInstance;
- (ClientMsgReadAck*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientMsgReadAckBuilder*) builder;
+ (ClientMsgReadAckBuilder*) builder;
+ (ClientMsgReadAckBuilder*) builderWithPrototype:(ClientMsgReadAck*) prototype;
- (ClientMsgReadAckBuilder*) toBuilder;

+ (ClientMsgReadAck*) parseFromData:(NSData*) data;
+ (ClientMsgReadAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgReadAck*) parseFromInputStream:(NSInputStream*) input;
+ (ClientMsgReadAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientMsgReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientMsgReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientMsgReadAckBuilder : PBGeneratedMessageBuilder {
@private
  ClientMsgReadAck* result;
}

- (ClientMsgReadAck*) defaultInstance;

- (ClientMsgReadAckBuilder*) clear;
- (ClientMsgReadAckBuilder*) clone;

- (ClientMsgReadAck*) build;
- (ClientMsgReadAck*) buildPartial;

- (ClientMsgReadAckBuilder*) mergeFrom:(ClientMsgReadAck*) other;
- (ClientMsgReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientMsgReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (ClientMsgReadAckBuilder*) setCmdId:(SInt32) value;
- (ClientMsgReadAckBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientMsgReadAckBuilder*) setFromUserId:(NSString*) value;
- (ClientMsgReadAckBuilder*) clearFromUserId;
@end

@interface ClientP2PCmdMsg : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasCmdMsgData_:1;
  BOOL hasSeqNo_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  NSString* toUserId;
  NSData* cmdMsgData;
  UInt32 seqNo;
}
- (BOOL) hasCmdId;
- (BOOL) hasSeqNo;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasCmdMsgData;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 seqNo;
@property (readonly, strong) NSString* fromUserId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) NSData* cmdMsgData;

+ (ClientP2PCmdMsg*) defaultInstance;
- (ClientP2PCmdMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientP2PCmdMsgBuilder*) builder;
+ (ClientP2PCmdMsgBuilder*) builder;
+ (ClientP2PCmdMsgBuilder*) builderWithPrototype:(ClientP2PCmdMsg*) prototype;
- (ClientP2PCmdMsgBuilder*) toBuilder;

+ (ClientP2PCmdMsg*) parseFromData:(NSData*) data;
+ (ClientP2PCmdMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientP2PCmdMsg*) parseFromInputStream:(NSInputStream*) input;
+ (ClientP2PCmdMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientP2PCmdMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientP2PCmdMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientP2PCmdMsgBuilder : PBGeneratedMessageBuilder {
@private
  ClientP2PCmdMsg* result;
}

- (ClientP2PCmdMsg*) defaultInstance;

- (ClientP2PCmdMsgBuilder*) clear;
- (ClientP2PCmdMsgBuilder*) clone;

- (ClientP2PCmdMsg*) build;
- (ClientP2PCmdMsg*) buildPartial;

- (ClientP2PCmdMsgBuilder*) mergeFrom:(ClientP2PCmdMsg*) other;
- (ClientP2PCmdMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientP2PCmdMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (ClientP2PCmdMsgBuilder*) setCmdId:(SInt32) value;
- (ClientP2PCmdMsgBuilder*) clearCmdId;

- (BOOL) hasSeqNo;
- (UInt32) seqNo;
- (ClientP2PCmdMsgBuilder*) setSeqNo:(UInt32) value;
- (ClientP2PCmdMsgBuilder*) clearSeqNo;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (ClientP2PCmdMsgBuilder*) setFromUserId:(NSString*) value;
- (ClientP2PCmdMsgBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (ClientP2PCmdMsgBuilder*) setToUserId:(NSString*) value;
- (ClientP2PCmdMsgBuilder*) clearToUserId;

- (BOOL) hasCmdMsgData;
- (NSData*) cmdMsgData;
- (ClientP2PCmdMsgBuilder*) setCmdMsgData:(NSData*) value;
- (ClientP2PCmdMsgBuilder*) clearCmdMsgData;
@end

@interface C2MTimeReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MTimeReq*) defaultInstance;
- (C2MTimeReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MTimeReqBuilder*) builder;
+ (C2MTimeReqBuilder*) builder;
+ (C2MTimeReqBuilder*) builderWithPrototype:(C2MTimeReq*) prototype;
- (C2MTimeReqBuilder*) toBuilder;

+ (C2MTimeReq*) parseFromData:(NSData*) data;
+ (C2MTimeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MTimeReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MTimeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MTimeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MTimeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MTimeReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MTimeReq* result;
}

- (C2MTimeReq*) defaultInstance;

- (C2MTimeReqBuilder*) clear;
- (C2MTimeReqBuilder*) clone;

- (C2MTimeReq*) build;
- (C2MTimeReq*) buildPartial;

- (C2MTimeReqBuilder*) mergeFrom:(C2MTimeReq*) other;
- (C2MTimeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MTimeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MTimeReqBuilder*) setCmdId:(SInt32) value;
- (C2MTimeReqBuilder*) clearCmdId;
@end

@interface C2MTimeRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasServerTime_:1;
  SInt32 cmdId;
  UInt32 serverTime;
}
- (BOOL) hasCmdId;
- (BOOL) hasServerTime;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 serverTime;

+ (C2MTimeRsp*) defaultInstance;
- (C2MTimeRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MTimeRspBuilder*) builder;
+ (C2MTimeRspBuilder*) builder;
+ (C2MTimeRspBuilder*) builderWithPrototype:(C2MTimeRsp*) prototype;
- (C2MTimeRspBuilder*) toBuilder;

+ (C2MTimeRsp*) parseFromData:(NSData*) data;
+ (C2MTimeRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MTimeRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MTimeRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MTimeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MTimeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MTimeRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MTimeRsp* result;
}

- (C2MTimeRsp*) defaultInstance;

- (C2MTimeRspBuilder*) clear;
- (C2MTimeRspBuilder*) clone;

- (C2MTimeRsp*) build;
- (C2MTimeRsp*) buildPartial;

- (C2MTimeRspBuilder*) mergeFrom:(C2MTimeRsp*) other;
- (C2MTimeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MTimeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MTimeRspBuilder*) setCmdId:(SInt32) value;
- (C2MTimeRspBuilder*) clearCmdId;

- (BOOL) hasServerTime;
- (UInt32) serverTime;
- (C2MTimeRspBuilder*) setServerTime:(UInt32) value;
- (C2MTimeRspBuilder*) clearServerTime;
@end

@interface C2MUnReadMsgCntReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MUnReadMsgCntReq*) defaultInstance;
- (C2MUnReadMsgCntReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUnReadMsgCntReqBuilder*) builder;
+ (C2MUnReadMsgCntReqBuilder*) builder;
+ (C2MUnReadMsgCntReqBuilder*) builderWithPrototype:(C2MUnReadMsgCntReq*) prototype;
- (C2MUnReadMsgCntReqBuilder*) toBuilder;

+ (C2MUnReadMsgCntReq*) parseFromData:(NSData*) data;
+ (C2MUnReadMsgCntReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgCntReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUnReadMsgCntReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUnReadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUnReadMsgCntReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MUnReadMsgCntReq* result;
}

- (C2MUnReadMsgCntReq*) defaultInstance;

- (C2MUnReadMsgCntReqBuilder*) clear;
- (C2MUnReadMsgCntReqBuilder*) clone;

- (C2MUnReadMsgCntReq*) build;
- (C2MUnReadMsgCntReq*) buildPartial;

- (C2MUnReadMsgCntReqBuilder*) mergeFrom:(C2MUnReadMsgCntReq*) other;
- (C2MUnReadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUnReadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUnReadMsgCntReqBuilder*) setCmdId:(SInt32) value;
- (C2MUnReadMsgCntReqBuilder*) clearCmdId;
@end

@interface C2MUnReadMsgCntRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * unreadListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * unreadList;
- (ClientUnReadInfo*)unreadListAtIndex:(NSUInteger)index;

+ (C2MUnReadMsgCntRsp*) defaultInstance;
- (C2MUnReadMsgCntRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUnReadMsgCntRspBuilder*) builder;
+ (C2MUnReadMsgCntRspBuilder*) builder;
+ (C2MUnReadMsgCntRspBuilder*) builderWithPrototype:(C2MUnReadMsgCntRsp*) prototype;
- (C2MUnReadMsgCntRspBuilder*) toBuilder;

+ (C2MUnReadMsgCntRsp*) parseFromData:(NSData*) data;
+ (C2MUnReadMsgCntRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUnReadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUnReadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUnReadMsgCntRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MUnReadMsgCntRsp* result;
}

- (C2MUnReadMsgCntRsp*) defaultInstance;

- (C2MUnReadMsgCntRspBuilder*) clear;
- (C2MUnReadMsgCntRspBuilder*) clone;

- (C2MUnReadMsgCntRsp*) build;
- (C2MUnReadMsgCntRsp*) buildPartial;

- (C2MUnReadMsgCntRspBuilder*) mergeFrom:(C2MUnReadMsgCntRsp*) other;
- (C2MUnReadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUnReadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUnReadMsgCntRspBuilder*) setCmdId:(SInt32) value;
- (C2MUnReadMsgCntRspBuilder*) clearCmdId;

- (NSMutableArray *)unreadList;
- (ClientUnReadInfo*)unreadListAtIndex:(NSUInteger)index;
- (C2MUnReadMsgCntRspBuilder *)addUnreadList:(ClientUnReadInfo*)value;
- (C2MUnReadMsgCntRspBuilder *)setUnreadListArray:(NSArray *)array;
- (C2MUnReadMsgCntRspBuilder *)clearUnreadList;
@end

@interface C2MUnReadMsgReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  SInt32 cmdId;
  NSString* fromUserId;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;

+ (C2MUnReadMsgReq*) defaultInstance;
- (C2MUnReadMsgReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUnReadMsgReqBuilder*) builder;
+ (C2MUnReadMsgReqBuilder*) builder;
+ (C2MUnReadMsgReqBuilder*) builderWithPrototype:(C2MUnReadMsgReq*) prototype;
- (C2MUnReadMsgReqBuilder*) toBuilder;

+ (C2MUnReadMsgReq*) parseFromData:(NSData*) data;
+ (C2MUnReadMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUnReadMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUnReadMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUnReadMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUnReadMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MUnReadMsgReq* result;
}

- (C2MUnReadMsgReq*) defaultInstance;

- (C2MUnReadMsgReqBuilder*) clear;
- (C2MUnReadMsgReqBuilder*) clone;

- (C2MUnReadMsgReq*) build;
- (C2MUnReadMsgReq*) buildPartial;

- (C2MUnReadMsgReqBuilder*) mergeFrom:(C2MUnReadMsgReq*) other;
- (C2MUnReadMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUnReadMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUnReadMsgReqBuilder*) setCmdId:(SInt32) value;
- (C2MUnReadMsgReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MUnReadMsgReqBuilder*) setFromUserId:(NSString*) value;
- (C2MUnReadMsgReqBuilder*) clearFromUserId;
@end

@interface C2MHistoryMsgReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasMsgOffset_:1;
  BOOL hasMsgCount_:1;
  SInt32 cmdId;
  NSString* fromUserId;
  UInt32 msgOffset;
  UInt32 msgCount;
}
- (BOOL) hasCmdId;
- (BOOL) hasFromUserId;
- (BOOL) hasMsgOffset;
- (BOOL) hasMsgCount;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* fromUserId;
@property (readonly) UInt32 msgOffset;
@property (readonly) UInt32 msgCount;

+ (C2MHistoryMsgReq*) defaultInstance;
- (C2MHistoryMsgReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MHistoryMsgReqBuilder*) builder;
+ (C2MHistoryMsgReqBuilder*) builder;
+ (C2MHistoryMsgReqBuilder*) builderWithPrototype:(C2MHistoryMsgReq*) prototype;
- (C2MHistoryMsgReqBuilder*) toBuilder;

+ (C2MHistoryMsgReq*) parseFromData:(NSData*) data;
+ (C2MHistoryMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MHistoryMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MHistoryMsgReq* result;
}

- (C2MHistoryMsgReq*) defaultInstance;

- (C2MHistoryMsgReqBuilder*) clear;
- (C2MHistoryMsgReqBuilder*) clone;

- (C2MHistoryMsgReq*) build;
- (C2MHistoryMsgReq*) buildPartial;

- (C2MHistoryMsgReqBuilder*) mergeFrom:(C2MHistoryMsgReq*) other;
- (C2MHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MHistoryMsgReqBuilder*) setCmdId:(SInt32) value;
- (C2MHistoryMsgReqBuilder*) clearCmdId;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (C2MHistoryMsgReqBuilder*) setFromUserId:(NSString*) value;
- (C2MHistoryMsgReqBuilder*) clearFromUserId;

- (BOOL) hasMsgOffset;
- (UInt32) msgOffset;
- (C2MHistoryMsgReqBuilder*) setMsgOffset:(UInt32) value;
- (C2MHistoryMsgReqBuilder*) clearMsgOffset;

- (BOOL) hasMsgCount;
- (UInt32) msgCount;
- (C2MHistoryMsgReqBuilder*) setMsgCount:(UInt32) value;
- (C2MHistoryMsgReqBuilder*) clearMsgCount;
@end

@interface C2MMsgListRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasDisplayUserId_:1;
  SInt32 cmdId;
  NSString* displayUserId;
  NSMutableArray * msgListArray;
}
- (BOOL) hasCmdId;
- (BOOL) hasDisplayUserId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSString* displayUserId;
@property (readonly, strong) NSArray * msgList;
- (ClientMsgInfo*)msgListAtIndex:(NSUInteger)index;

+ (C2MMsgListRsp*) defaultInstance;
- (C2MMsgListRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MMsgListRspBuilder*) builder;
+ (C2MMsgListRspBuilder*) builder;
+ (C2MMsgListRspBuilder*) builderWithPrototype:(C2MMsgListRsp*) prototype;
- (C2MMsgListRspBuilder*) toBuilder;

+ (C2MMsgListRsp*) parseFromData:(NSData*) data;
+ (C2MMsgListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MMsgListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MMsgListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MMsgListRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MMsgListRsp* result;
}

- (C2MMsgListRsp*) defaultInstance;

- (C2MMsgListRspBuilder*) clear;
- (C2MMsgListRspBuilder*) clone;

- (C2MMsgListRsp*) build;
- (C2MMsgListRsp*) buildPartial;

- (C2MMsgListRspBuilder*) mergeFrom:(C2MMsgListRsp*) other;
- (C2MMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MMsgListRspBuilder*) setCmdId:(SInt32) value;
- (C2MMsgListRspBuilder*) clearCmdId;

- (BOOL) hasDisplayUserId;
- (NSString*) displayUserId;
- (C2MMsgListRspBuilder*) setDisplayUserId:(NSString*) value;
- (C2MMsgListRspBuilder*) clearDisplayUserId;

- (NSMutableArray *)msgList;
- (ClientMsgInfo*)msgListAtIndex:(NSUInteger)index;
- (C2MMsgListRspBuilder *)addMsgList:(ClientMsgInfo*)value;
- (C2MMsgListRspBuilder *)setMsgListArray:(NSArray *)array;
- (C2MMsgListRspBuilder *)clearMsgList;
@end

@interface C2MAllUserReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;

+ (C2MAllUserReq*) defaultInstance;
- (C2MAllUserReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MAllUserReqBuilder*) builder;
+ (C2MAllUserReqBuilder*) builder;
+ (C2MAllUserReqBuilder*) builderWithPrototype:(C2MAllUserReq*) prototype;
- (C2MAllUserReqBuilder*) toBuilder;

+ (C2MAllUserReq*) parseFromData:(NSData*) data;
+ (C2MAllUserReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MAllUserReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MAllUserReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MAllUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MAllUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MAllUserReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MAllUserReq* result;
}

- (C2MAllUserReq*) defaultInstance;

- (C2MAllUserReqBuilder*) clear;
- (C2MAllUserReqBuilder*) clone;

- (C2MAllUserReq*) build;
- (C2MAllUserReq*) buildPartial;

- (C2MAllUserReqBuilder*) mergeFrom:(C2MAllUserReq*) other;
- (C2MAllUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MAllUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MAllUserReqBuilder*) setCmdId:(SInt32) value;
- (C2MAllUserReqBuilder*) clearCmdId;
@end

@interface C2MUserInfoReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * userIdListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) PBArray * userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;

+ (C2MUserInfoReq*) defaultInstance;
- (C2MUserInfoReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserInfoReqBuilder*) builder;
+ (C2MUserInfoReqBuilder*) builder;
+ (C2MUserInfoReqBuilder*) builderWithPrototype:(C2MUserInfoReq*) prototype;
- (C2MUserInfoReqBuilder*) toBuilder;

+ (C2MUserInfoReq*) parseFromData:(NSData*) data;
+ (C2MUserInfoReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserInfoReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserInfoReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserInfoReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserInfoReq* result;
}

- (C2MUserInfoReq*) defaultInstance;

- (C2MUserInfoReqBuilder*) clear;
- (C2MUserInfoReqBuilder*) clone;

- (C2MUserInfoReq*) build;
- (C2MUserInfoReq*) buildPartial;

- (C2MUserInfoReqBuilder*) mergeFrom:(C2MUserInfoReq*) other;
- (C2MUserInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserInfoReqBuilder*) setCmdId:(SInt32) value;
- (C2MUserInfoReqBuilder*) clearCmdId;

- (NSMutableArray *)userIdList;
- (NSString*)userIdListAtIndex:(NSUInteger)index;
- (C2MUserInfoReqBuilder *)addUserIdList:(NSString*)value;
- (C2MUserInfoReqBuilder *)setUserIdListArray:(NSArray *)array;
- (C2MUserInfoReqBuilder *)clearUserIdList;
@end

@interface C2MUserInfoRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  SInt32 cmdId;
  NSMutableArray * userInfoListArray;
}
- (BOOL) hasCmdId;
@property (readonly) SInt32 cmdId;
@property (readonly, strong) NSArray * userInfoList;
- (ClientUserInfo*)userInfoListAtIndex:(NSUInteger)index;

+ (C2MUserInfoRsp*) defaultInstance;
- (C2MUserInfoRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MUserInfoRspBuilder*) builder;
+ (C2MUserInfoRspBuilder*) builder;
+ (C2MUserInfoRspBuilder*) builderWithPrototype:(C2MUserInfoRsp*) prototype;
- (C2MUserInfoRspBuilder*) toBuilder;

+ (C2MUserInfoRsp*) parseFromData:(NSData*) data;
+ (C2MUserInfoRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserInfoRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MUserInfoRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MUserInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MUserInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MUserInfoRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MUserInfoRsp* result;
}

- (C2MUserInfoRsp*) defaultInstance;

- (C2MUserInfoRspBuilder*) clear;
- (C2MUserInfoRspBuilder*) clone;

- (C2MUserInfoRsp*) build;
- (C2MUserInfoRsp*) buildPartial;

- (C2MUserInfoRspBuilder*) mergeFrom:(C2MUserInfoRsp*) other;
- (C2MUserInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MUserInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MUserInfoRspBuilder*) setCmdId:(SInt32) value;
- (C2MUserInfoRspBuilder*) clearCmdId;

- (NSMutableArray *)userInfoList;
- (ClientUserInfo*)userInfoListAtIndex:(NSUInteger)index;
- (C2MUserInfoRspBuilder *)addUserInfoList:(ClientUserInfo*)value;
- (C2MUserInfoRspBuilder *)setUserInfoListArray:(NSArray *)array;
- (C2MUserInfoRspBuilder *)clearUserInfoList;
@end

@interface C2MDBQueryReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasQueryData_:1;
  BOOL hasSeqNo_:1;
  SInt32 cmdId;
  NSData* queryData;
  UInt32 seqNo;
}
- (BOOL) hasCmdId;
- (BOOL) hasSeqNo;
- (BOOL) hasQueryData;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 seqNo;
@property (readonly, strong) NSData* queryData;

+ (C2MDBQueryReq*) defaultInstance;
- (C2MDBQueryReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MDBQueryReqBuilder*) builder;
+ (C2MDBQueryReqBuilder*) builder;
+ (C2MDBQueryReqBuilder*) builderWithPrototype:(C2MDBQueryReq*) prototype;
- (C2MDBQueryReqBuilder*) toBuilder;

+ (C2MDBQueryReq*) parseFromData:(NSData*) data;
+ (C2MDBQueryReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MDBQueryReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MDBQueryReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MDBQueryReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MDBQueryReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MDBQueryReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MDBQueryReq* result;
}

- (C2MDBQueryReq*) defaultInstance;

- (C2MDBQueryReqBuilder*) clear;
- (C2MDBQueryReqBuilder*) clone;

- (C2MDBQueryReq*) build;
- (C2MDBQueryReq*) buildPartial;

- (C2MDBQueryReqBuilder*) mergeFrom:(C2MDBQueryReq*) other;
- (C2MDBQueryReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MDBQueryReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MDBQueryReqBuilder*) setCmdId:(SInt32) value;
- (C2MDBQueryReqBuilder*) clearCmdId;

- (BOOL) hasSeqNo;
- (UInt32) seqNo;
- (C2MDBQueryReqBuilder*) setSeqNo:(UInt32) value;
- (C2MDBQueryReqBuilder*) clearSeqNo;

- (BOOL) hasQueryData;
- (NSData*) queryData;
- (C2MDBQueryReqBuilder*) setQueryData:(NSData*) value;
- (C2MDBQueryReqBuilder*) clearQueryData;
@end

@interface C2MDBQueryRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasResultData_:1;
  BOOL hasSeqNo_:1;
  SInt32 cmdId;
  NSData* resultData;
  UInt32 seqNo;
}
- (BOOL) hasCmdId;
- (BOOL) hasSeqNo;
- (BOOL) hasResultData;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 seqNo;
@property (readonly, strong) NSData* resultData;

+ (C2MDBQueryRsp*) defaultInstance;
- (C2MDBQueryRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MDBQueryRspBuilder*) builder;
+ (C2MDBQueryRspBuilder*) builder;
+ (C2MDBQueryRspBuilder*) builderWithPrototype:(C2MDBQueryRsp*) prototype;
- (C2MDBQueryRspBuilder*) toBuilder;

+ (C2MDBQueryRsp*) parseFromData:(NSData*) data;
+ (C2MDBQueryRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MDBQueryRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MDBQueryRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MDBQueryRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MDBQueryRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MDBQueryRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MDBQueryRsp* result;
}

- (C2MDBQueryRsp*) defaultInstance;

- (C2MDBQueryRspBuilder*) clear;
- (C2MDBQueryRspBuilder*) clone;

- (C2MDBQueryRsp*) build;
- (C2MDBQueryRsp*) buildPartial;

- (C2MDBQueryRspBuilder*) mergeFrom:(C2MDBQueryRsp*) other;
- (C2MDBQueryRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MDBQueryRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MDBQueryRspBuilder*) setCmdId:(SInt32) value;
- (C2MDBQueryRspBuilder*) clearCmdId;

- (BOOL) hasSeqNo;
- (UInt32) seqNo;
- (C2MDBQueryRspBuilder*) setSeqNo:(UInt32) value;
- (C2MDBQueryRspBuilder*) clearSeqNo;

- (BOOL) hasResultData;
- (NSData*) resultData;
- (C2MDBQueryRspBuilder*) setResultData:(NSData*) value;
- (C2MDBQueryRspBuilder*) clearResultData;
@end

@interface C2MRemoveSessionReq : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasSessionId_:1;
  BOOL hasSessionType_:1;
  SInt32 cmdId;
  NSString* sessionId;
  SessionType sessionType;
}
- (BOOL) hasCmdId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
@property (readonly) SInt32 cmdId;
@property (readonly) SessionType sessionType;
@property (readonly, strong) NSString* sessionId;

+ (C2MRemoveSessionReq*) defaultInstance;
- (C2MRemoveSessionReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MRemoveSessionReqBuilder*) builder;
+ (C2MRemoveSessionReqBuilder*) builder;
+ (C2MRemoveSessionReqBuilder*) builderWithPrototype:(C2MRemoveSessionReq*) prototype;
- (C2MRemoveSessionReqBuilder*) toBuilder;

+ (C2MRemoveSessionReq*) parseFromData:(NSData*) data;
+ (C2MRemoveSessionReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MRemoveSessionReq*) parseFromInputStream:(NSInputStream*) input;
+ (C2MRemoveSessionReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MRemoveSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MRemoveSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MRemoveSessionReqBuilder : PBGeneratedMessageBuilder {
@private
  C2MRemoveSessionReq* result;
}

- (C2MRemoveSessionReq*) defaultInstance;

- (C2MRemoveSessionReqBuilder*) clear;
- (C2MRemoveSessionReqBuilder*) clone;

- (C2MRemoveSessionReq*) build;
- (C2MRemoveSessionReq*) buildPartial;

- (C2MRemoveSessionReqBuilder*) mergeFrom:(C2MRemoveSessionReq*) other;
- (C2MRemoveSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MRemoveSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MRemoveSessionReqBuilder*) setCmdId:(SInt32) value;
- (C2MRemoveSessionReqBuilder*) clearCmdId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (C2MRemoveSessionReqBuilder*) setSessionType:(SessionType) value;
- (C2MRemoveSessionReqBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (C2MRemoveSessionReqBuilder*) setSessionId:(NSString*) value;
- (C2MRemoveSessionReqBuilder*) clearSessionId;
@end

@interface C2MRemoveSessionRsp : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasSessionId_:1;
  BOOL hasResults_:1;
  BOOL hasSessionType_:1;
  SInt32 cmdId;
  NSString* sessionId;
  UInt32 results;
  SessionType sessionType;
}
- (BOOL) hasCmdId;
- (BOOL) hasResults;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 results;
@property (readonly) SessionType sessionType;
@property (readonly, strong) NSString* sessionId;

+ (C2MRemoveSessionRsp*) defaultInstance;
- (C2MRemoveSessionRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MRemoveSessionRspBuilder*) builder;
+ (C2MRemoveSessionRspBuilder*) builder;
+ (C2MRemoveSessionRspBuilder*) builderWithPrototype:(C2MRemoveSessionRsp*) prototype;
- (C2MRemoveSessionRspBuilder*) toBuilder;

+ (C2MRemoveSessionRsp*) parseFromData:(NSData*) data;
+ (C2MRemoveSessionRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MRemoveSessionRsp*) parseFromInputStream:(NSInputStream*) input;
+ (C2MRemoveSessionRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MRemoveSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MRemoveSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MRemoveSessionRspBuilder : PBGeneratedMessageBuilder {
@private
  C2MRemoveSessionRsp* result;
}

- (C2MRemoveSessionRsp*) defaultInstance;

- (C2MRemoveSessionRspBuilder*) clear;
- (C2MRemoveSessionRspBuilder*) clone;

- (C2MRemoveSessionRsp*) build;
- (C2MRemoveSessionRsp*) buildPartial;

- (C2MRemoveSessionRspBuilder*) mergeFrom:(C2MRemoveSessionRsp*) other;
- (C2MRemoveSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MRemoveSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MRemoveSessionRspBuilder*) setCmdId:(SInt32) value;
- (C2MRemoveSessionRspBuilder*) clearCmdId;

- (BOOL) hasResults;
- (UInt32) results;
- (C2MRemoveSessionRspBuilder*) setResults:(UInt32) value;
- (C2MRemoveSessionRspBuilder*) clearResults;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (C2MRemoveSessionRspBuilder*) setSessionType:(SessionType) value;
- (C2MRemoveSessionRspBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (C2MRemoveSessionRspBuilder*) setSessionId:(NSString*) value;
- (C2MRemoveSessionRspBuilder*) clearSessionId;
@end

@interface C2MServiceSetting : PBGeneratedMessage {
@private
  BOOL hasCmdId_:1;
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  SInt32 cmdId;
  UInt32 key;
  UInt32 value;
}
- (BOOL) hasCmdId;
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly) SInt32 cmdId;
@property (readonly) UInt32 key;
@property (readonly) UInt32 value;

+ (C2MServiceSetting*) defaultInstance;
- (C2MServiceSetting*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (C2MServiceSettingBuilder*) builder;
+ (C2MServiceSettingBuilder*) builder;
+ (C2MServiceSettingBuilder*) builderWithPrototype:(C2MServiceSetting*) prototype;
- (C2MServiceSettingBuilder*) toBuilder;

+ (C2MServiceSetting*) parseFromData:(NSData*) data;
+ (C2MServiceSetting*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MServiceSetting*) parseFromInputStream:(NSInputStream*) input;
+ (C2MServiceSetting*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (C2MServiceSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (C2MServiceSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface C2MServiceSettingBuilder : PBGeneratedMessageBuilder {
@private
  C2MServiceSetting* result;
}

- (C2MServiceSetting*) defaultInstance;

- (C2MServiceSettingBuilder*) clear;
- (C2MServiceSettingBuilder*) clone;

- (C2MServiceSetting*) build;
- (C2MServiceSetting*) buildPartial;

- (C2MServiceSettingBuilder*) mergeFrom:(C2MServiceSetting*) other;
- (C2MServiceSettingBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (C2MServiceSettingBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmdId;
- (SInt32) cmdId;
- (C2MServiceSettingBuilder*) setCmdId:(SInt32) value;
- (C2MServiceSettingBuilder*) clearCmdId;

- (BOOL) hasKey;
- (UInt32) key;
- (C2MServiceSettingBuilder*) setKey:(UInt32) value;
- (C2MServiceSettingBuilder*) clearKey;

- (BOOL) hasValue;
- (UInt32) value;
- (C2MServiceSettingBuilder*) setValue:(UInt32) value;
- (C2MServiceSettingBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
